<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Exceptions;

use EasyBimehLandingLib\APIException;
use EasyBimehLandingLib\APIHelper;

/**
 * @todo Write general description for this model
 */
class Status400Exception extends APIException
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isSuccess public property
     */
    public $isSuccess;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $message public property
     */
    public $message;

    /**
     * @todo Write general description for this property
     * @var string|null $extraData public property
     */
    public $extraData;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\Exception $exception public property
     */
    public $exception;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct($reason, $context)
    {
        parent::__construct($reason, $context);
    }

    /**
     * Unbox response into this exception class
     */
    public function unbox()
    {
        APIHelper::deserialize(self::getResponseBody(), $this, false, false);
    }
}
