<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 *ساختار کلی پاسخ سرور
 */
class BaseModelUpload implements JsonSerializable
{
    /**
     * وضعیت موفقیت درخواست
     * @required
     * @var bool $isSuccess public property
     */
    public $isSuccess;

    /**
     * کد وضعیت درخواست
     * @required
     * @var integer $status public property
     */
    public $status;

    /**
     * بدنه ی اصلی درخواست که با توجه به نوع درخواست، تغییر می کند
     * @required
     * @var object $message public property
     */
    public $message;

    /**
     * اطلاعات اضافه ی درخواست
     * @var string|null $extraData public property
     */
    public $extraData;

    /**
     * اطلاعات خطاهای رخ داده
     * @var string|null $exception public property
     */
    public $exception;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool    $isSuccess Initialization value for $this->isSuccess
     * @param integer $status    Initialization value for $this->status
     * @param object  $message   Initialization value for $this->message
     * @param string  $extraData Initialization value for $this->extraData
     * @param string  $exception Initialization value for $this->exception
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->isSuccess = func_get_arg(0);
            $this->status    = func_get_arg(1);
            $this->message   = func_get_arg(2);
            $this->extraData = func_get_arg(3);
            $this->exception = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['isSuccess'] = $this->isSuccess;
        $json['status']    = $this->status;
        $json['message']   = $this->message;
        $json['extraData'] = $this->extraData;
        $json['exception'] = $this->exception;

        return $json;
    }
}
