<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DamageType implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @var string|null $sortPriority public property
     */
    public $sortPriority;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOn public property
     */
    public $createOn;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $updateOn public property
     */
    public $updateOn;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createdBy public property
     */
    public $createdBy;

    /**
     * @todo Write general description for this property
     * @var string|null $updatedBy public property
     */
    public $updatedBy;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $updateOnPersianDate public property
     */
    public $updateOnPersianDate;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                  Initialization value for $this->id
     * @param string  $title               Initialization value for $this->title
     * @param string  $sortPriority        Initialization value for $this->sortPriority
     * @param string  $createOn            Initialization value for $this->createOn
     * @param string  $updateOn            Initialization value for $this->updateOn
     * @param string  $createdBy           Initialization value for $this->createdBy
     * @param string  $updatedBy           Initialization value for $this->updatedBy
     * @param string  $createOnPersianDate Initialization value for $this->createOnPersianDate
     * @param string  $updateOnPersianDate Initialization value for $this->updateOnPersianDate
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->id                  = func_get_arg(0);
            $this->title               = func_get_arg(1);
            $this->sortPriority        = func_get_arg(2);
            $this->createOn            = func_get_arg(3);
            $this->updateOn            = func_get_arg(4);
            $this->createdBy           = func_get_arg(5);
            $this->updatedBy           = func_get_arg(6);
            $this->createOnPersianDate = func_get_arg(7);
            $this->updateOnPersianDate = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                  = $this->id;
        $json['title']               = $this->title;
        $json['sortPriority']        = $this->sortPriority;
        $json['createOn']            = $this->createOn;
        $json['updateOn']            = $this->updateOn;
        $json['createdBy']           = $this->createdBy;
        $json['updatedBy']           = $this->updatedBy;
        $json['createOnPersianDate'] = $this->createOnPersianDate;
        $json['updateOnPersianDate'] = $this->updateOnPersianDate;

        return $json;
    }
}
