<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ElectronicEquipmentInsurancePolicyFilter implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var integer|null $deviceTypeId public property
     */
    public $deviceTypeId;

    /**
     * @todo Write general description for this property
     * @var integer|null $deviceBrandId public property
     */
    public $deviceBrandId;

    /**
     * @todo Write general description for this property
     * @var integer|null $deviceModelId public property
     */
    public $deviceModelId;

    /**
     * @todo Write general description for this property
     * @var string|null $buildYear public property
     */
    public $buildYear;

    /**
     * @todo Write general description for this property
     * @var string|null $deviceValue public property
     */
    public $deviceValue;

    /**
     * @todo Write general description for this property
     * @var integer|null $franchiseeId public property
     */
    public $franchiseeId;

    /**
     * @todo Write general description for this property
     * @var integer|null $insuranceExtraCoverageIds public property
     */
    public $insuranceExtraCoverageIds;

    /**
     * @todo Write general description for this property
     * @var integer|null $policyTermId public property
     */
    public $policyTermId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreSubDomainName public property
     */
    public $insuranceCentreSubDomainName;

    /**
     * @todo Write general description for this property
     * @var integer|null $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @var integer|null $insuranceCompanyId public property
     */
    public $insuranceCompanyId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isSearchQuery public property
     */
    public $isSearchQuery;

    /**
     * @todo Write general description for this property
     * @var string|null $giftCode public property
     */
    public $giftCode;

    /**
     * @todo Write general description for this property
     * @var integer|null $customerUserId public property
     */
    public $customerUserId;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $deviceTypeId                 Initialization value for $this->deviceTypeId
     * @param integer $deviceBrandId                Initialization value for $this->deviceBrandId
     * @param integer $deviceModelId                Initialization value for $this->deviceModelId
     * @param string  $buildYear                    Initialization value for $this->buildYear
     * @param string  $deviceValue                  Initialization value for $this->deviceValue
     * @param integer $franchiseeId                 Initialization value for $this->franchiseeId
     * @param integer $insuranceExtraCoverageIds    Initialization value for $this->insuranceExtraCoverageIds
     * @param integer $policyTermId                 Initialization value for $this->policyTermId
     * @param string  $insuranceCentreSubDomainName Initialization value for $this->insuranceCentreSubDomainName
     * @param integer $insuranceCentreId            Initialization value for $this->insuranceCentreId
     * @param integer $insuranceCompanyId           Initialization value for $this->insuranceCompanyId
     * @param bool    $isSearchQuery                Initialization value for $this->isSearchQuery
     * @param string  $giftCode                     Initialization value for $this->giftCode
     * @param integer $customerUserId               Initialization value for $this->customerUserId
     */
    public function __construct()
    {
        if (14 == func_num_args()) {
            $this->deviceTypeId                 = func_get_arg(0);
            $this->deviceBrandId                = func_get_arg(1);
            $this->deviceModelId                = func_get_arg(2);
            $this->buildYear                    = func_get_arg(3);
            $this->deviceValue                  = func_get_arg(4);
            $this->franchiseeId                 = func_get_arg(5);
            $this->insuranceExtraCoverageIds    = func_get_arg(6);
            $this->policyTermId                 = func_get_arg(7);
            $this->insuranceCentreSubDomainName = func_get_arg(8);
            $this->insuranceCentreId            = func_get_arg(9);
            $this->insuranceCompanyId           = func_get_arg(10);
            $this->isSearchQuery                = func_get_arg(11);
            $this->giftCode                     = func_get_arg(12);
            $this->customerUserId               = func_get_arg(13);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['deviceTypeId']                 = $this->deviceTypeId;
        $json['deviceBrandId']                = $this->deviceBrandId;
        $json['deviceModelId']                = $this->deviceModelId;
        $json['buildYear']                    = $this->buildYear;
        $json['deviceValue']                  = $this->deviceValue;
        $json['franchiseeId']                 = $this->franchiseeId;
        $json['insuranceExtraCoverageIds']    = $this->insuranceExtraCoverageIds;
        $json['policyTermId']                 = $this->policyTermId;
        $json['insuranceCentreSubDomainName'] = $this->insuranceCentreSubDomainName;
        $json['insuranceCentreId']            = $this->insuranceCentreId;
        $json['insuranceCompanyId']           = $this->insuranceCompanyId;
        $json['isSearchQuery']                = $this->isSearchQuery;
        $json['giftCode']                     = $this->giftCode;
        $json['customerUserId']               = $this->customerUserId;

        return $json;
    }
}
