<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ElectronicEquipmentInsurancePolicyExtendView implements JsonSerializable
{
    /**
     * شناسه ی نوع دستگاه
     * @var integer|null $deviceTypeId public property
     */
    public $deviceTypeId;

    /**
     * شناسه ی برند دستگاه
     * @var integer|null $deviceBrandId public property
     */
    public $deviceBrandId;

    /**
     * شناسه ی مدل دستگاه
     * @var integer|null $deviceModelId public property
     */
    public $deviceModelId;

    /**
     * سریال دستگاه
     * @var string|null $deviceSerial public property
     */
    public $deviceSerial;

    /**
     * سال ساخت دستگاه
     * @var string|null $buildYear public property
     */
    public $buildYear;

    /**
     * @todo Write general description for this property
     * @var integer|null $deviceValue public property
     */
    public $deviceValue;

    /**
     * @todo Write general description for this property
     * @var integer|null $franchisee public property
     */
    public $franchisee;

    /**
     * @todo Write general description for this property
     * @var bool|null $hasWarranty public property
     */
    public $hasWarranty;

    /**
     * @todo Write general description for this property
     * @var string|null $warrantyCompany public property
     */
    public $warrantyCompany;

    /**
     * @todo Write general description for this property
     * @var string|null $serialInsuranceCard public property
     */
    public $serialInsuranceCard;

    /**
     * @todo Write general description for this property
     * @var integer|null $metaMediaBehindDeviceId public property
     */
    public $metaMediaBehindDeviceId;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaBehindDeviceUrl public property
     */
    public $metaMediaBehindDeviceUrl;

    /**
     * @todo Write general description for this property
     * @var integer|null $metaMediaOnDeviceId public property
     */
    public $metaMediaOnDeviceId;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaOnDeviceUrl public property
     */
    public $metaMediaOnDeviceUrl;

    /**
     * @todo Write general description for this property
     * @var integer|null $metaMediaDeviceBoxId public property
     */
    public $metaMediaDeviceBoxId;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaDeviceBoxUrl public property
     */
    public $metaMediaDeviceBoxUrl;

    /**
     * @todo Write general description for this property
     * @maps _InsuranceCoverageIds
     * @var string|null $insuranceCoverageIds public property
     */
    public $insuranceCoverageIds;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCoveragePrice public property
     */
    public $insuranceCoveragePrice;

    /**
     * @todo Write general description for this property
     * @var string|null $basePremium public property
     */
    public $basePremium;

    /**
     * @todo Write general description for this property
     * @var string|null $allPremium public property
     */
    public $allPremium;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $insuranceCompanyDiscountRate public property
     */
    public $insuranceCompanyDiscountRate;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCompanyDiscount public property
     */
    public $insuranceCompanyDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreDiscount public property
     */
    public $insuranceCentreDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $coupenDiscount public property
     */
    public $coupenDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $allDiscount public property
     */
    public $allDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $exchangePremium public property
     */
    public $exchangePremium;

    /**
     * @todo Write general description for this property
     * @var string|null $deviceTypeTitle public property
     */
    public $deviceTypeTitle;

    /**
     * @todo Write general description for this property
     * @var string|null $deviceBrandTitle public property
     */
    public $deviceBrandTitle;

    /**
     * @todo Write general description for this property
     * @var string|null $deviceModelTitle public property
     */
    public $deviceModelTitle;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $deviceTypeId                 Initialization value for $this->deviceTypeId
     * @param integer $deviceBrandId                Initialization value for $this->deviceBrandId
     * @param integer $deviceModelId                Initialization value for $this->deviceModelId
     * @param string  $deviceSerial                 Initialization value for $this->deviceSerial
     * @param string  $buildYear                    Initialization value for $this->buildYear
     * @param integer $deviceValue                  Initialization value for $this->deviceValue
     * @param integer $franchisee                   Initialization value for $this->franchisee
     * @param bool    $hasWarranty                  Initialization value for $this->hasWarranty
     * @param string  $warrantyCompany              Initialization value for $this->warrantyCompany
     * @param string  $serialInsuranceCard          Initialization value for $this->serialInsuranceCard
     * @param integer $metaMediaBehindDeviceId      Initialization value for $this->metaMediaBehindDeviceId
     * @param string  $metaMediaBehindDeviceUrl     Initialization value for $this->metaMediaBehindDeviceUrl
     * @param integer $metaMediaOnDeviceId          Initialization value for $this->metaMediaOnDeviceId
     * @param string  $metaMediaOnDeviceUrl         Initialization value for $this->metaMediaOnDeviceUrl
     * @param integer $metaMediaDeviceBoxId         Initialization value for $this->metaMediaDeviceBoxId
     * @param string  $metaMediaDeviceBoxUrl        Initialization value for $this->metaMediaDeviceBoxUrl
     * @param string  $insuranceCoverageIds         Initialization value for $this->insuranceCoverageIds
     * @param string  $insuranceCoveragePrice       Initialization value for $this->insuranceCoveragePrice
     * @param string  $basePremium                  Initialization value for $this->basePremium
     * @param string  $allPremium                   Initialization value for $this->allPremium
     * @param string  $insuranceCompanyDiscountRate Initialization value for $this->insuranceCompanyDiscountRate
     * @param integer $insuranceCompanyDiscount     Initialization value for $this->insuranceCompanyDiscount
     * @param integer $insuranceCentreDiscount      Initialization value for $this->insuranceCentreDiscount
     * @param integer $coupenDiscount               Initialization value for $this->coupenDiscount
     * @param integer $allDiscount                  Initialization value for $this->allDiscount
     * @param integer $exchangePremium              Initialization value for $this->exchangePremium
     * @param string  $deviceTypeTitle              Initialization value for $this->deviceTypeTitle
     * @param string  $deviceBrandTitle             Initialization value for $this->deviceBrandTitle
     * @param string  $deviceModelTitle             Initialization value for $this->deviceModelTitle
     */
    public function __construct()
    {
        if (29 == func_num_args()) {
            $this->deviceTypeId                 = func_get_arg(0);
            $this->deviceBrandId                = func_get_arg(1);
            $this->deviceModelId                = func_get_arg(2);
            $this->deviceSerial                 = func_get_arg(3);
            $this->buildYear                    = func_get_arg(4);
            $this->deviceValue                  = func_get_arg(5);
            $this->franchisee                   = func_get_arg(6);
            $this->hasWarranty                  = func_get_arg(7);
            $this->warrantyCompany              = func_get_arg(8);
            $this->serialInsuranceCard          = func_get_arg(9);
            $this->metaMediaBehindDeviceId      = func_get_arg(10);
            $this->metaMediaBehindDeviceUrl     = func_get_arg(11);
            $this->metaMediaOnDeviceId          = func_get_arg(12);
            $this->metaMediaOnDeviceUrl         = func_get_arg(13);
            $this->metaMediaDeviceBoxId         = func_get_arg(14);
            $this->metaMediaDeviceBoxUrl        = func_get_arg(15);
            $this->insuranceCoverageIds         = func_get_arg(16);
            $this->insuranceCoveragePrice       = func_get_arg(17);
            $this->basePremium                  = func_get_arg(18);
            $this->allPremium                   = func_get_arg(19);
            $this->insuranceCompanyDiscountRate = func_get_arg(20);
            $this->insuranceCompanyDiscount     = func_get_arg(21);
            $this->insuranceCentreDiscount      = func_get_arg(22);
            $this->coupenDiscount               = func_get_arg(23);
            $this->allDiscount                  = func_get_arg(24);
            $this->exchangePremium              = func_get_arg(25);
            $this->deviceTypeTitle              = func_get_arg(26);
            $this->deviceBrandTitle             = func_get_arg(27);
            $this->deviceModelTitle             = func_get_arg(28);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['deviceTypeId']                 = $this->deviceTypeId;
        $json['deviceBrandId']                = $this->deviceBrandId;
        $json['deviceModelId']                = $this->deviceModelId;
        $json['deviceSerial']                 = $this->deviceSerial;
        $json['buildYear']                    = $this->buildYear;
        $json['deviceValue']                  = $this->deviceValue;
        $json['franchisee']                   = $this->franchisee;
        $json['hasWarranty']                  = $this->hasWarranty;
        $json['warrantyCompany']              = $this->warrantyCompany;
        $json['serialInsuranceCard']          = $this->serialInsuranceCard;
        $json['metaMediaBehindDeviceId']      = $this->metaMediaBehindDeviceId;
        $json['metaMediaBehindDeviceUrl']     = $this->metaMediaBehindDeviceUrl;
        $json['metaMediaOnDeviceId']          = $this->metaMediaOnDeviceId;
        $json['metaMediaOnDeviceUrl']         = $this->metaMediaOnDeviceUrl;
        $json['metaMediaDeviceBoxId']         = $this->metaMediaDeviceBoxId;
        $json['metaMediaDeviceBoxUrl']        = $this->metaMediaDeviceBoxUrl;
        $json['_InsuranceCoverageIds']        = $this->insuranceCoverageIds;
        $json['insuranceCoveragePrice']       = $this->insuranceCoveragePrice;
        $json['basePremium']                  = $this->basePremium;
        $json['allPremium']                   = $this->allPremium;
        $json['insuranceCompanyDiscountRate'] = $this->insuranceCompanyDiscountRate;
        $json['insuranceCompanyDiscount']     = $this->insuranceCompanyDiscount;
        $json['insuranceCentreDiscount']      = $this->insuranceCentreDiscount;
        $json['coupenDiscount']               = $this->coupenDiscount;
        $json['allDiscount']                  = $this->allDiscount;
        $json['exchangePremium']              = $this->exchangePremium;
        $json['deviceTypeTitle']              = $this->deviceTypeTitle;
        $json['deviceBrandTitle']             = $this->deviceBrandTitle;
        $json['deviceModelTitle']             = $this->deviceModelTitle;

        return $json;
    }
}
