<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ElevatorInsurance implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $hasPlan public property
     */
    public $hasPlan;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ComboDataModel[] $buildingUseTypes public property
     */
    public $buildingUseTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ElevatorType[] $elevatorTypes public property
     */
    public $elevatorTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\DefectOrganCoverage[] $defectOrganCoverage public property
     */
    public $defectOrganCoverage;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\DeathCapitalCoverage[] $deathCapitalCoverage public property
     */
    public $deathCapitalCoverage;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\FinancialCoverage[] $financialCoverage public property
     */
    public $financialCoverage;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\MedicalCostCoverage[] $medicalCostCoverage public property
     */
    public $medicalCostCoverage;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceRiskLevel[] $insuranceRiskLevels public property
     */
    public $insuranceRiskLevels;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyTerm[] $insurancePolicyTerms public property
     */
    public $insurancePolicyTerms;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceCompany[] $insuranceCompanies public property
     */
    public $insuranceCompanies;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\Province[] $provinces public property
     */
    public $provinces;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $cities public property
     */
    public $cities;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $cityRegions public property
     */
    public $cityRegions;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ShippingType[] $shippingTypes public property
     */
    public $shippingTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\PostType[] $postTypes public property
     */
    public $postTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyCondition $insurancePolicyCondition public property
     */
    public $insurancePolicyCondition;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceDataElevatorInsurance $insuranceData public property
     */
    public $insuranceData;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool                           $hasPlan                  Initialization value for $this->hasPlan
     * @param array                          $buildingUseTypes         Initialization value for $this-
     *                                                                   >buildingUseTypes
     * @param array                          $elevatorTypes            Initialization value for $this->elevatorTypes
     * @param array                          $defectOrganCoverage      Initialization value for $this-
     *                                                                   >defectOrganCoverage
     * @param array                          $deathCapitalCoverage     Initialization value for $this-
     *                                                                   >deathCapitalCoverage
     * @param array                          $financialCoverage        Initialization value for $this-
     *                                                                   >financialCoverage
     * @param array                          $medicalCostCoverage      Initialization value for $this-
     *                                                                   >medicalCostCoverage
     * @param array                          $insuranceRiskLevels      Initialization value for $this-
     *                                                                   >insuranceRiskLevels
     * @param array                          $insurancePolicyTerms     Initialization value for $this-
     *                                                                   >insurancePolicyTerms
     * @param array                          $insuranceCompanies       Initialization value for $this-
     *                                                                   >insuranceCompanies
     * @param array                          $provinces                Initialization value for $this->provinces
     * @param array                          $cities                   Initialization value for $this->cities
     * @param array                          $cityRegions              Initialization value for $this->cityRegions
     * @param array                          $shippingTypes            Initialization value for $this->shippingTypes
     * @param array                          $postTypes                Initialization value for $this->postTypes
     * @param InsurancePolicyCondition       $insurancePolicyCondition Initialization value for $this-
     *                                                                   >insurancePolicyCondition
     * @param InsuranceDataElevatorInsurance $insuranceData            Initialization value for $this->insuranceData
     */
    public function __construct()
    {
        if (17 == func_num_args()) {
            $this->hasPlan                  = func_get_arg(0);
            $this->buildingUseTypes         = func_get_arg(1);
            $this->elevatorTypes            = func_get_arg(2);
            $this->defectOrganCoverage      = func_get_arg(3);
            $this->deathCapitalCoverage     = func_get_arg(4);
            $this->financialCoverage        = func_get_arg(5);
            $this->medicalCostCoverage      = func_get_arg(6);
            $this->insuranceRiskLevels      = func_get_arg(7);
            $this->insurancePolicyTerms     = func_get_arg(8);
            $this->insuranceCompanies       = func_get_arg(9);
            $this->provinces                = func_get_arg(10);
            $this->cities                   = func_get_arg(11);
            $this->cityRegions              = func_get_arg(12);
            $this->shippingTypes            = func_get_arg(13);
            $this->postTypes                = func_get_arg(14);
            $this->insurancePolicyCondition = func_get_arg(15);
            $this->insuranceData            = func_get_arg(16);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['hasPlan']                  = $this->hasPlan;
        $json['buildingUseTypes']         = $this->buildingUseTypes;
        $json['elevatorTypes']            = $this->elevatorTypes;
        $json['defectOrganCoverage']      = $this->defectOrganCoverage;
        $json['deathCapitalCoverage']     = $this->deathCapitalCoverage;
        $json['financialCoverage']        = $this->financialCoverage;
        $json['medicalCostCoverage']      = $this->medicalCostCoverage;
        $json['insuranceRiskLevels']      = $this->insuranceRiskLevels;
        $json['insurancePolicyTerms']     = $this->insurancePolicyTerms;
        $json['insuranceCompanies']       = $this->insuranceCompanies;
        $json['provinces']                = $this->provinces;
        $json['cities']                   = $this->cities;
        $json['cityRegions']              = $this->cityRegions;
        $json['shippingTypes']            = $this->shippingTypes;
        $json['postTypes']                = $this->postTypes;
        $json['insurancePolicyCondition'] = $this->insurancePolicyCondition;
        $json['insuranceData']            = $this->insuranceData;

        return $json;
    }
}
