<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ElevatorInsurancePolicyFilter implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $buildingUseTypeParamId public property
     */
    public $buildingUseTypeParamId;

    /**
     * @todo Write general description for this property
     * @var string|null $elevatorTypeParamId public property
     */
    public $elevatorTypeParamId;

    /**
     * @todo Write general description for this property
     * @var string|null $floors public property
     */
    public $floors;

    /**
     * @todo Write general description for this property
     * @var string|null $elevatorCapacityCargo public property
     */
    public $elevatorCapacityCargo;

    /**
     * @todo Write general description for this property
     * @var string|null $elevatorCapacity public property
     */
    public $elevatorCapacity;

    /**
     * @todo Write general description for this property
     * @var string|null $riskLevelId public property
     */
    public $riskLevelId;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePolicyTerms public property
     */
    public $insurancePolicyTerms;

    /**
     * @todo Write general description for this property
     * @var string|null $defectOrganCoverageId public property
     */
    public $defectOrganCoverageId;

    /**
     * @todo Write general description for this property
     * @var string|null $deathCapitalCoverageId public property
     */
    public $deathCapitalCoverageId;

    /**
     * @todo Write general description for this property
     * @var string|null $financialCoverageId public property
     */
    public $financialCoverageId;

    /**
     * @todo Write general description for this property
     * @var string|null $medicalCostCoverageId public property
     */
    public $medicalCostCoverageId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $ownerCoverage public property
     */
    public $ownerCoverage;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceExtraCoverageIds public property
     */
    public $insuranceExtraCoverageIds;

    /**
     * @todo Write general description for this property
     * @var string|null $policyTermId public property
     */
    public $policyTermId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreSubDomainName public property
     */
    public $insuranceCentreSubDomainName;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCompanyId public property
     */
    public $insuranceCompanyId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isSearchQuery public property
     */
    public $isSearchQuery;

    /**
     * @todo Write general description for this property
     * @var string|null $giftCode public property
     */
    public $giftCode;

    /**
     * @todo Write general description for this property
     * @var string|null $customerUserId public property
     */
    public $customerUserId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $buildingUseTypeParamId       Initialization value for $this->buildingUseTypeParamId
     * @param string $elevatorTypeParamId          Initialization value for $this->elevatorTypeParamId
     * @param string $floors                       Initialization value for $this->floors
     * @param string $elevatorCapacityCargo        Initialization value for $this->elevatorCapacityCargo
     * @param string $elevatorCapacity             Initialization value for $this->elevatorCapacity
     * @param string $riskLevelId                  Initialization value for $this->riskLevelId
     * @param string $insurancePolicyTerms         Initialization value for $this->insurancePolicyTerms
     * @param string $defectOrganCoverageId        Initialization value for $this->defectOrganCoverageId
     * @param string $deathCapitalCoverageId       Initialization value for $this->deathCapitalCoverageId
     * @param string $financialCoverageId          Initialization value for $this->financialCoverageId
     * @param string $medicalCostCoverageId        Initialization value for $this->medicalCostCoverageId
     * @param bool   $ownerCoverage                Initialization value for $this->ownerCoverage
     * @param string $insuranceExtraCoverageIds    Initialization value for $this->insuranceExtraCoverageIds
     * @param string $policyTermId                 Initialization value for $this->policyTermId
     * @param string $insuranceCentreSubDomainName Initialization value for $this->insuranceCentreSubDomainName
     * @param string $insuranceCentreId            Initialization value for $this->insuranceCentreId
     * @param string $insuranceCompanyId           Initialization value for $this->insuranceCompanyId
     * @param bool   $isSearchQuery                Initialization value for $this->isSearchQuery
     * @param string $giftCode                     Initialization value for $this->giftCode
     * @param string $customerUserId               Initialization value for $this->customerUserId
     */
    public function __construct()
    {
        if (20 == func_num_args()) {
            $this->buildingUseTypeParamId       = func_get_arg(0);
            $this->elevatorTypeParamId          = func_get_arg(1);
            $this->floors                       = func_get_arg(2);
            $this->elevatorCapacityCargo        = func_get_arg(3);
            $this->elevatorCapacity             = func_get_arg(4);
            $this->riskLevelId                  = func_get_arg(5);
            $this->insurancePolicyTerms         = func_get_arg(6);
            $this->defectOrganCoverageId        = func_get_arg(7);
            $this->deathCapitalCoverageId       = func_get_arg(8);
            $this->financialCoverageId          = func_get_arg(9);
            $this->medicalCostCoverageId        = func_get_arg(10);
            $this->ownerCoverage                = func_get_arg(11);
            $this->insuranceExtraCoverageIds    = func_get_arg(12);
            $this->policyTermId                 = func_get_arg(13);
            $this->insuranceCentreSubDomainName = func_get_arg(14);
            $this->insuranceCentreId            = func_get_arg(15);
            $this->insuranceCompanyId           = func_get_arg(16);
            $this->isSearchQuery                = func_get_arg(17);
            $this->giftCode                     = func_get_arg(18);
            $this->customerUserId               = func_get_arg(19);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['buildingUseTypeParamId']       = $this->buildingUseTypeParamId;
        $json['elevatorTypeParamId']          = $this->elevatorTypeParamId;
        $json['floors']                       = $this->floors;
        $json['elevatorCapacityCargo']        = $this->elevatorCapacityCargo;
        $json['elevatorCapacity']             = $this->elevatorCapacity;
        $json['riskLevelId']                  = $this->riskLevelId;
        $json['insurancePolicyTerms']         = $this->insurancePolicyTerms;
        $json['defectOrganCoverageId']        = $this->defectOrganCoverageId;
        $json['deathCapitalCoverageId']       = $this->deathCapitalCoverageId;
        $json['financialCoverageId']          = $this->financialCoverageId;
        $json['medicalCostCoverageId']        = $this->medicalCostCoverageId;
        $json['ownerCoverage']                = $this->ownerCoverage;
        $json['insuranceExtraCoverageIds']    = $this->insuranceExtraCoverageIds;
        $json['policyTermId']                 = $this->policyTermId;
        $json['insuranceCentreSubDomainName'] = $this->insuranceCentreSubDomainName;
        $json['insuranceCentreId']            = $this->insuranceCentreId;
        $json['insuranceCompanyId']           = $this->insuranceCompanyId;
        $json['isSearchQuery']                = $this->isSearchQuery;
        $json['giftCode']                     = $this->giftCode;
        $json['customerUserId']               = $this->customerUserId;

        return $json;
    }
}
