<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class EverySquareMeterCoverage implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $fiscalYearId public property
     */
    public $fiscalYearId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCoverageId public property
     */
    public $insuranceCoverageId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $coverageRial public property
     */
    public $coverageRial;

    /**
     * @todo Write general description for this property
     * @var string|null $coverageEuro public property
     */
    public $coverageEuro;

    /**
     * @todo Write general description for this property
     * @var string|null $fromPrice public property
     */
    public $fromPrice;

    /**
     * @todo Write general description for this property
     * @var string|null $toPrice public property
     */
    public $toPrice;

    /**
     * @todo Write general description for this property
     * @var string|null $isDiscount public property
     */
    public $isDiscount;

    /**
     * @todo Write general description for this property
     * @var string|null $coverageValueType public property
     */
    public $coverageValueType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $coverageStringValue public property
     */
    public $coverageStringValue;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceTypeIds public property
     */
    public $insuranceTypeIds;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCompanyIds public property
     */
    public $insuranceCompanyIds;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $selected public property
     */
    public $selected;

    /**
     * @todo Write general description for this property
     * @var string|null $isVisible public property
     */
    public $isVisible;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceTypeId public property
     */
    public $insuranceTypeId;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePlansIds public property
     */
    public $insurancePlansIds;

    /**
     * @todo Write general description for this property
     * @var string|null $isActive public property
     */
    public $isActive;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceTypeTitles public property
     */
    public $insuranceTypeTitles;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCompanyTitles public property
     */
    public $insuranceCompanyTitles;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePlanTitles public property
     */
    public $insurancePlanTitles;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceTypeTitle public property
     */
    public $insuranceTypeTitle;

    /**
     * @todo Write general description for this property
     * @var string|null $createdBy public property
     */
    public $createdBy;

    /**
     * @todo Write general description for this property
     * @var string|null $isPlan public property
     */
    public $isPlan;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                     Initialization value for $this->id
     * @param integer $fiscalYearId           Initialization value for $this->fiscalYearId
     * @param integer $insuranceCoverageId    Initialization value for $this->insuranceCoverageId
     * @param integer $coverageRial           Initialization value for $this->coverageRial
     * @param string  $coverageEuro           Initialization value for $this->coverageEuro
     * @param string  $fromPrice              Initialization value for $this->fromPrice
     * @param string  $toPrice                Initialization value for $this->toPrice
     * @param string  $isDiscount             Initialization value for $this->isDiscount
     * @param string  $coverageValueType      Initialization value for $this->coverageValueType
     * @param string  $coverageStringValue    Initialization value for $this->coverageStringValue
     * @param string  $insuranceTypeIds       Initialization value for $this->insuranceTypeIds
     * @param string  $insuranceCompanyIds    Initialization value for $this->insuranceCompanyIds
     * @param bool    $selected               Initialization value for $this->selected
     * @param string  $isVisible              Initialization value for $this->isVisible
     * @param string  $insuranceTypeId        Initialization value for $this->insuranceTypeId
     * @param string  $insurancePlansIds      Initialization value for $this->insurancePlansIds
     * @param string  $isActive               Initialization value for $this->isActive
     * @param string  $insuranceTypeTitles    Initialization value for $this->insuranceTypeTitles
     * @param string  $insuranceCompanyTitles Initialization value for $this->insuranceCompanyTitles
     * @param string  $insurancePlanTitles    Initialization value for $this->insurancePlanTitles
     * @param string  $insuranceTypeTitle     Initialization value for $this->insuranceTypeTitle
     * @param string  $createdBy              Initialization value for $this->createdBy
     * @param string  $isPlan                 Initialization value for $this->isPlan
     */
    public function __construct()
    {
        if (23 == func_num_args()) {
            $this->id                     = func_get_arg(0);
            $this->fiscalYearId           = func_get_arg(1);
            $this->insuranceCoverageId    = func_get_arg(2);
            $this->coverageRial           = func_get_arg(3);
            $this->coverageEuro           = func_get_arg(4);
            $this->fromPrice              = func_get_arg(5);
            $this->toPrice                = func_get_arg(6);
            $this->isDiscount             = func_get_arg(7);
            $this->coverageValueType      = func_get_arg(8);
            $this->coverageStringValue    = func_get_arg(9);
            $this->insuranceTypeIds       = func_get_arg(10);
            $this->insuranceCompanyIds    = func_get_arg(11);
            $this->selected               = func_get_arg(12);
            $this->isVisible              = func_get_arg(13);
            $this->insuranceTypeId        = func_get_arg(14);
            $this->insurancePlansIds      = func_get_arg(15);
            $this->isActive               = func_get_arg(16);
            $this->insuranceTypeTitles    = func_get_arg(17);
            $this->insuranceCompanyTitles = func_get_arg(18);
            $this->insurancePlanTitles    = func_get_arg(19);
            $this->insuranceTypeTitle     = func_get_arg(20);
            $this->createdBy              = func_get_arg(21);
            $this->isPlan                 = func_get_arg(22);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                     = $this->id;
        $json['fiscalYearId']           = $this->fiscalYearId;
        $json['insuranceCoverageId']    = $this->insuranceCoverageId;
        $json['coverageRial']           = $this->coverageRial;
        $json['coverageEuro']           = $this->coverageEuro;
        $json['fromPrice']              = $this->fromPrice;
        $json['toPrice']                = $this->toPrice;
        $json['isDiscount']             = $this->isDiscount;
        $json['coverageValueType']      = $this->coverageValueType;
        $json['coverageStringValue']    = $this->coverageStringValue;
        $json['insuranceTypeIds']       = $this->insuranceTypeIds;
        $json['insuranceCompanyIds']    = $this->insuranceCompanyIds;
        $json['selected']               = $this->selected;
        $json['isVisible']              = $this->isVisible;
        $json['insuranceTypeId']        = $this->insuranceTypeId;
        $json['insurancePlansIds']      = $this->insurancePlansIds;
        $json['isActive']               = $this->isActive;
        $json['insuranceTypeTitles']    = $this->insuranceTypeTitles;
        $json['insuranceCompanyTitles'] = $this->insuranceCompanyTitles;
        $json['insurancePlanTitles']    = $this->insurancePlanTitles;
        $json['insuranceTypeTitle']     = $this->insuranceTypeTitle;
        $json['createdBy']              = $this->createdBy;
        $json['isPlan']                 = $this->isPlan;

        return $json;
    }
}
