<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 *با توجه به API ممکن از تغییر کند
 */
class Exception implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $dateTime public property
     */
    public $dateTime;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $message public property
     */
    public $message;

    /**
     * @todo Write general description for this property
     * @var string|null $helpLink public property
     */
    public $helpLink;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $source public property
     */
    public $source;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $stackTrace public property
     */
    public $stackTrace;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\TargetSite $targetSite public property
     */
    public $targetSite;

    /**
     * @todo Write general description for this property
     * @var string|null $errorLine public property
     */
    public $errorLine;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $exceptionType public property
     */
    public $exceptionType;

    /**
     * @todo Write general description for this property
     * @var string|null $exceptionUrl public property
     */
    public $exceptionUrl;

    /**
     * @todo Write general description for this property
     * @var string|null $innerException public property
     */
    public $innerException;

    /**
     * Constructor to set initial or default values of member properties
     * @param string     $dateTime       Initialization value for $this->dateTime
     * @param string     $message        Initialization value for $this->message
     * @param string     $helpLink       Initialization value for $this->helpLink
     * @param string     $source         Initialization value for $this->source
     * @param string     $stackTrace     Initialization value for $this->stackTrace
     * @param TargetSite $targetSite     Initialization value for $this->targetSite
     * @param string     $errorLine      Initialization value for $this->errorLine
     * @param string     $exceptionType  Initialization value for $this->exceptionType
     * @param string     $exceptionUrl   Initialization value for $this->exceptionUrl
     * @param string     $innerException Initialization value for $this->innerException
     */
    public function __construct()
    {
        if (10 == func_num_args()) {
            $this->dateTime       = func_get_arg(0);
            $this->message        = func_get_arg(1);
            $this->helpLink       = func_get_arg(2);
            $this->source         = func_get_arg(3);
            $this->stackTrace     = func_get_arg(4);
            $this->targetSite     = func_get_arg(5);
            $this->errorLine      = func_get_arg(6);
            $this->exceptionType  = func_get_arg(7);
            $this->exceptionUrl   = func_get_arg(8);
            $this->innerException = func_get_arg(9);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['dateTime']       = $this->dateTime;
        $json['message']        = $this->message;
        $json['helpLink']       = $this->helpLink;
        $json['source']         = $this->source;
        $json['stackTrace']     = $this->stackTrace;
        $json['targetSite']     = $this->targetSite;
        $json['errorLine']      = $this->errorLine;
        $json['exceptionType']  = $this->exceptionType;
        $json['exceptionUrl']   = $this->exceptionUrl;
        $json['innerException'] = $this->innerException;

        return $json;
    }
}
