<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 *با توجه به API ممکن است تغییر کند
 */
class ExtraData implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $aliasName public property
     */
    public $aliasName;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $aliasName Initialization value for $this->aliasName
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->aliasName = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['aliasName'] = $this->aliasName;

        return $json;
    }
}
