<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ExtraDataBaseModelPortalLandingPage implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $hasPlan public property
     */
    public $hasPlan;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool $hasPlan Initialization value for $this->hasPlan
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->hasPlan = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['hasPlan'] = $this->hasPlan;

        return $json;
    }
}
