<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ExtraDataBaseModelInsuranceCentrePolicyTypes implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceTypesCount public property
     */
    public $insuranceTypesCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $hasPlan public property
     */
    public $hasPlan;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $insuranceTypesCount Initialization value for $this->insuranceTypesCount
     * @param bool    $hasPlan             Initialization value for $this->hasPlan
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->insuranceTypesCount = func_get_arg(0);
            $this->hasPlan             = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['insuranceTypesCount'] = $this->insuranceTypesCount;
        $json['hasPlan']             = $this->hasPlan;

        return $json;
    }
}
