<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class FaqInsuranceCentre implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $question public property
     */
    public $question;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $answer public property
     */
    public $answer;

    /**
     * @todo Write general description for this property
     * @var integer|null $sortPriority public property
     */
    public $sortPriority;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $questionGroupParamId public property
     */
    public $questionGroupParamId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isActive public property
     */
    public $isActive;

    /**
     * @todo Write general description for this property
     * @var string|null $theInsuranceCentre public property
     */
    public $theInsuranceCentre;

    /**
     * @todo Write general description for this property
     * @var string|null $theQuestionGroupParam public property
     */
    public $theQuestionGroupParam;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOn public property
     */
    public $createOn;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $updateOn public property
     */
    public $updateOn;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createdBy public property
     */
    public $createdBy;

    /**
     * @todo Write general description for this property
     * @var string|null $updatedBy public property
     */
    public $updatedBy;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $updateOnPersianDate public property
     */
    public $updateOnPersianDate;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                    Initialization value for $this->id
     * @param integer $insuranceCentreId     Initialization value for $this->insuranceCentreId
     * @param string  $question              Initialization value for $this->question
     * @param string  $answer                Initialization value for $this->answer
     * @param integer $sortPriority          Initialization value for $this->sortPriority
     * @param integer $questionGroupParamId  Initialization value for $this->questionGroupParamId
     * @param bool    $isActive              Initialization value for $this->isActive
     * @param string  $theInsuranceCentre    Initialization value for $this->theInsuranceCentre
     * @param string  $theQuestionGroupParam Initialization value for $this->theQuestionGroupParam
     * @param string  $createOn              Initialization value for $this->createOn
     * @param string  $updateOn              Initialization value for $this->updateOn
     * @param string  $createdBy             Initialization value for $this->createdBy
     * @param string  $updatedBy             Initialization value for $this->updatedBy
     * @param string  $createOnPersianDate   Initialization value for $this->createOnPersianDate
     * @param string  $updateOnPersianDate   Initialization value for $this->updateOnPersianDate
     */
    public function __construct()
    {
        if (15 == func_num_args()) {
            $this->id                    = func_get_arg(0);
            $this->insuranceCentreId     = func_get_arg(1);
            $this->question              = func_get_arg(2);
            $this->answer                = func_get_arg(3);
            $this->sortPriority          = func_get_arg(4);
            $this->questionGroupParamId  = func_get_arg(5);
            $this->isActive              = func_get_arg(6);
            $this->theInsuranceCentre    = func_get_arg(7);
            $this->theQuestionGroupParam = func_get_arg(8);
            $this->createOn              = func_get_arg(9);
            $this->updateOn              = func_get_arg(10);
            $this->createdBy             = func_get_arg(11);
            $this->updatedBy             = func_get_arg(12);
            $this->createOnPersianDate   = func_get_arg(13);
            $this->updateOnPersianDate   = func_get_arg(14);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                    = $this->id;
        $json['insuranceCentreId']     = $this->insuranceCentreId;
        $json['question']              = $this->question;
        $json['answer']                = $this->answer;
        $json['sortPriority']          = $this->sortPriority;
        $json['questionGroupParamId']  = $this->questionGroupParamId;
        $json['isActive']              = $this->isActive;
        $json['theInsuranceCentre']    = $this->theInsuranceCentre;
        $json['theQuestionGroupParam'] = $this->theQuestionGroupParam;
        $json['createOn']              = $this->createOn;
        $json['updateOn']              = $this->updateOn;
        $json['createdBy']             = $this->createdBy;
        $json['updatedBy']             = $this->updatedBy;
        $json['createOnPersianDate']   = $this->createOnPersianDate;
        $json['updateOnPersianDate']   = $this->updateOnPersianDate;

        return $json;
    }
}
