<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class FireInsurancePolicyExtendView implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $buildingTypeParamId public property
     */
    public $buildingTypeParamId;

    /**
     * @todo Write general description for this property
     * @var string|null $skeletonTypeBuildingParamId public property
     */
    public $skeletonTypeBuildingParamId;

    /**
     * @todo Write general description for this property
     * @var string|null $buildingUseTypeParamId public property
     */
    public $buildingUseTypeParamId;

    /**
     * @todo Write general description for this property
     * @var string|null $unitCount public property
     */
    public $unitCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $everySquareMeterCoverageRateId public property
     */
    public $everySquareMeterCoverageRateId;

    /**
     * @todo Write general description for this property
     * @var string|null $cityId public property
     */
    public $cityId;

    /**
     * @todo Write general description for this property
     * @var string|null $provinceId public property
     */
    public $provinceId;

    /**
     * @todo Write general description for this property
     * @var string|null $buildingArea public property
     */
    public $buildingArea;

    /**
     * @todo Write general description for this property
     * @var string|null $valueOfAppliancesFurnishing public property
     */
    public $valueOfAppliancesFurnishing;

    /**
     * @todo Write general description for this property
     * @maps _InsuranceCoverageIds
     * @var string|null $insuranceCoverageIds public property
     */
    public $insuranceCoverageIds;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $onlyAppliancesFurnishings public property
     */
    public $onlyAppliancesFurnishings;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCoveragePrice public property
     */
    public $insuranceCoveragePrice;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePolicyCommitmentCeiling public property
     */
    public $insurancePolicyCommitmentCeiling;

    /**
     * @todo Write general description for this property
     * @var string|null $valuePerSquareMeterRate public property
     */
    public $valuePerSquareMeterRate;

    /**
     * @todo Write general description for this property
     * @var string|null $buildYear public property
     */
    public $buildYear;

    /**
     * @todo Write general description for this property
     * @var string|null $zipCode public property
     */
    public $zipCode;

    /**
     * @todo Write general description for this property
     * @var string|null $addressPlaceBuilding public property
     */
    public $addressPlaceBuilding;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $riskLevelDiscount public property
     */
    public $riskLevelDiscount;

    /**
     * @todo Write general description for this property
     * @var string|null $basePremium public property
     */
    public $basePremium;

    /**
     * @todo Write general description for this property
     * @var string|null $allPremium public property
     */
    public $allPremium;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCompanyDiscountRate public property
     */
    public $insuranceCompanyDiscountRate;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCompanyDiscount public property
     */
    public $insuranceCompanyDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreDiscount public property
     */
    public $insuranceCentreDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $coupenDiscount public property
     */
    public $coupenDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $allDiscount public property
     */
    public $allDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $exchangePremium public property
     */
    public $exchangePremium;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $buildingTypeParamId              Initialization value for $this->buildingTypeParamId
     * @param string  $skeletonTypeBuildingParamId      Initialization value for $this->skeletonTypeBuildingParamId
     * @param string  $buildingUseTypeParamId           Initialization value for $this->buildingUseTypeParamId
     * @param string  $unitCount                        Initialization value for $this->unitCount
     * @param integer $everySquareMeterCoverageRateId   Initialization value for $this-
     *                                                    >everySquareMeterCoverageRateId
     * @param string  $cityId                           Initialization value for $this->cityId
     * @param string  $provinceId                       Initialization value for $this->provinceId
     * @param string  $buildingArea                     Initialization value for $this->buildingArea
     * @param string  $valueOfAppliancesFurnishing      Initialization value for $this->valueOfAppliancesFurnishing
     * @param string  $insuranceCoverageIds             Initialization value for $this->insuranceCoverageIds
     * @param bool    $onlyAppliancesFurnishings        Initialization value for $this->onlyAppliancesFurnishings
     * @param string  $insuranceCoveragePrice           Initialization value for $this->insuranceCoveragePrice
     * @param string  $insurancePolicyCommitmentCeiling Initialization value for $this-
     *                                                    >insurancePolicyCommitmentCeiling
     * @param string  $valuePerSquareMeterRate          Initialization value for $this->valuePerSquareMeterRate
     * @param string  $buildYear                        Initialization value for $this->buildYear
     * @param string  $zipCode                          Initialization value for $this->zipCode
     * @param string  $addressPlaceBuilding             Initialization value for $this->addressPlaceBuilding
     * @param integer $riskLevelDiscount                Initialization value for $this->riskLevelDiscount
     * @param string  $basePremium                      Initialization value for $this->basePremium
     * @param string  $allPremium                       Initialization value for $this->allPremium
     * @param integer $insuranceCompanyDiscountRate     Initialization value for $this->insuranceCompanyDiscountRate
     * @param integer $insuranceCompanyDiscount         Initialization value for $this->insuranceCompanyDiscount
     * @param integer $insuranceCentreDiscount          Initialization value for $this->insuranceCentreDiscount
     * @param integer $coupenDiscount                   Initialization value for $this->coupenDiscount
     * @param integer $allDiscount                      Initialization value for $this->allDiscount
     * @param integer $exchangePremium                  Initialization value for $this->exchangePremium
     */
    public function __construct()
    {
        if (26 == func_num_args()) {
            $this->buildingTypeParamId              = func_get_arg(0);
            $this->skeletonTypeBuildingParamId      = func_get_arg(1);
            $this->buildingUseTypeParamId           = func_get_arg(2);
            $this->unitCount                        = func_get_arg(3);
            $this->everySquareMeterCoverageRateId   = func_get_arg(4);
            $this->cityId                           = func_get_arg(5);
            $this->provinceId                       = func_get_arg(6);
            $this->buildingArea                     = func_get_arg(7);
            $this->valueOfAppliancesFurnishing      = func_get_arg(8);
            $this->insuranceCoverageIds             = func_get_arg(9);
            $this->onlyAppliancesFurnishings        = func_get_arg(10);
            $this->insuranceCoveragePrice           = func_get_arg(11);
            $this->insurancePolicyCommitmentCeiling = func_get_arg(12);
            $this->valuePerSquareMeterRate          = func_get_arg(13);
            $this->buildYear                        = func_get_arg(14);
            $this->zipCode                          = func_get_arg(15);
            $this->addressPlaceBuilding             = func_get_arg(16);
            $this->riskLevelDiscount                = func_get_arg(17);
            $this->basePremium                      = func_get_arg(18);
            $this->allPremium                       = func_get_arg(19);
            $this->insuranceCompanyDiscountRate     = func_get_arg(20);
            $this->insuranceCompanyDiscount         = func_get_arg(21);
            $this->insuranceCentreDiscount          = func_get_arg(22);
            $this->coupenDiscount                   = func_get_arg(23);
            $this->allDiscount                      = func_get_arg(24);
            $this->exchangePremium                  = func_get_arg(25);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['buildingTypeParamId']              = $this->buildingTypeParamId;
        $json['skeletonTypeBuildingParamId']      = $this->skeletonTypeBuildingParamId;
        $json['buildingUseTypeParamId']           = $this->buildingUseTypeParamId;
        $json['unitCount']                        = $this->unitCount;
        $json['everySquareMeterCoverageRateId']   = $this->everySquareMeterCoverageRateId;
        $json['cityId']                           = $this->cityId;
        $json['provinceId']                       = $this->provinceId;
        $json['buildingArea']                     = $this->buildingArea;
        $json['valueOfAppliancesFurnishing']      = $this->valueOfAppliancesFurnishing;
        $json['_InsuranceCoverageIds']            = $this->insuranceCoverageIds;
        $json['onlyAppliancesFurnishings']        = $this->onlyAppliancesFurnishings;
        $json['insuranceCoveragePrice']           = $this->insuranceCoveragePrice;
        $json['insurancePolicyCommitmentCeiling'] = $this->insurancePolicyCommitmentCeiling;
        $json['valuePerSquareMeterRate']          = $this->valuePerSquareMeterRate;
        $json['buildYear']                        = $this->buildYear;
        $json['zipCode']                          = $this->zipCode;
        $json['addressPlaceBuilding']             = $this->addressPlaceBuilding;
        $json['riskLevelDiscount']                = $this->riskLevelDiscount;
        $json['basePremium']                      = $this->basePremium;
        $json['allPremium']                       = $this->allPremium;
        $json['insuranceCompanyDiscountRate']     = $this->insuranceCompanyDiscountRate;
        $json['insuranceCompanyDiscount']         = $this->insuranceCompanyDiscount;
        $json['insuranceCentreDiscount']          = $this->insuranceCentreDiscount;
        $json['coupenDiscount']                   = $this->coupenDiscount;
        $json['allDiscount']                      = $this->allDiscount;
        $json['exchangePremium']                  = $this->exchangePremium;

        return $json;
    }
}
