<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class FireInsurance implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $hasPlan public property
     */
    public $hasPlan;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreProvinceId public property
     */
    public $insuranceCentreProvinceId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreCityId public property
     */
    public $insuranceCentreCityId;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ComboDataModel[] $insuranceCentreCities public property
     */
    public $insuranceCentreCities;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ComboDataModel[] $buildingTypes public property
     */
    public $buildingTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ComboDataModel[] $skeletonTypeBuildings public property
     */
    public $skeletonTypeBuildings;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ComboDataModel[] $buildingUseTypes public property
     */
    public $buildingUseTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyTerm[] $insurancePolicyTerms public property
     */
    public $insurancePolicyTerms;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceExtraCoverage[] $insuranceExtraCoverage public property
     */
    public $insuranceExtraCoverage;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\EverySquareMeterCoverage[] $everySquareMeterCoverage public property
     */
    public $everySquareMeterCoverage;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\Province[] $provinces public property
     */
    public $provinces;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $cities public property
     */
    public $cities;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $cityRegions public property
     */
    public $cityRegions;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ShippingType[] $shippingTypes public property
     */
    public $shippingTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\PostType[] $postTypes public property
     */
    public $postTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyCondition $insurancePolicyCondition public property
     */
    public $insurancePolicyCondition;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceDataFireInsurance $insuranceData public property
     */
    public $insuranceData;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool                       $hasPlan                   Initialization value for $this->hasPlan
     * @param integer                    $insuranceCentreProvinceId Initialization value for $this-
     *                                                                >insuranceCentreProvinceId
     * @param integer                    $insuranceCentreCityId     Initialization value for $this-
     *                                                                >insuranceCentreCityId
     * @param array                      $insuranceCentreCities     Initialization value for $this-
     *                                                                >insuranceCentreCities
     * @param array                      $buildingTypes             Initialization value for $this->buildingTypes
     * @param array                      $skeletonTypeBuildings     Initialization value for $this-
     *                                                                >skeletonTypeBuildings
     * @param array                      $buildingUseTypes          Initialization value for $this->buildingUseTypes
     * @param array                      $insurancePolicyTerms      Initialization value for $this-
     *                                                                >insurancePolicyTerms
     * @param array                      $insuranceExtraCoverage    Initialization value for $this-
     *                                                                >insuranceExtraCoverage
     * @param array                      $everySquareMeterCoverage  Initialization value for $this-
     *                                                                >everySquareMeterCoverage
     * @param array                      $provinces                 Initialization value for $this->provinces
     * @param array                      $cities                    Initialization value for $this->cities
     * @param array                      $cityRegions               Initialization value for $this->cityRegions
     * @param array                      $shippingTypes             Initialization value for $this->shippingTypes
     * @param array                      $postTypes                 Initialization value for $this->postTypes
     * @param InsurancePolicyCondition   $insurancePolicyCondition  Initialization value for $this-
     *                                                                >insurancePolicyCondition
     * @param InsuranceDataFireInsurance $insuranceData             Initialization value for $this->insuranceData
     */
    public function __construct()
    {
        if (17 == func_num_args()) {
            $this->hasPlan                   = func_get_arg(0);
            $this->insuranceCentreProvinceId = func_get_arg(1);
            $this->insuranceCentreCityId     = func_get_arg(2);
            $this->insuranceCentreCities     = func_get_arg(3);
            $this->buildingTypes             = func_get_arg(4);
            $this->skeletonTypeBuildings     = func_get_arg(5);
            $this->buildingUseTypes          = func_get_arg(6);
            $this->insurancePolicyTerms      = func_get_arg(7);
            $this->insuranceExtraCoverage    = func_get_arg(8);
            $this->everySquareMeterCoverage  = func_get_arg(9);
            $this->provinces                 = func_get_arg(10);
            $this->cities                    = func_get_arg(11);
            $this->cityRegions               = func_get_arg(12);
            $this->shippingTypes             = func_get_arg(13);
            $this->postTypes                 = func_get_arg(14);
            $this->insurancePolicyCondition  = func_get_arg(15);
            $this->insuranceData             = func_get_arg(16);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['hasPlan']                   = $this->hasPlan;
        $json['insuranceCentreProvinceId'] = $this->insuranceCentreProvinceId;
        $json['insuranceCentreCityId']     = $this->insuranceCentreCityId;
        $json['insuranceCentreCities']     = $this->insuranceCentreCities;
        $json['buildingTypes']             = $this->buildingTypes;
        $json['skeletonTypeBuildings']     = $this->skeletonTypeBuildings;
        $json['buildingUseTypes']          = $this->buildingUseTypes;
        $json['insurancePolicyTerms']      = $this->insurancePolicyTerms;
        $json['insuranceExtraCoverage']    = $this->insuranceExtraCoverage;
        $json['everySquareMeterCoverage']  = $this->everySquareMeterCoverage;
        $json['provinces']                 = $this->provinces;
        $json['cities']                    = $this->cities;
        $json['cityRegions']               = $this->cityRegions;
        $json['shippingTypes']             = $this->shippingTypes;
        $json['postTypes']                 = $this->postTypes;
        $json['insurancePolicyCondition']  = $this->insurancePolicyCondition;
        $json['insuranceData']             = $this->insuranceData;

        return $json;
    }
}
