<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class InsuranceCentre implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $personId public property
     */
    public $personId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $personalityType public property
     */
    public $personalityType;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreType public property
     */
    public $insuranceCentreType;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $registerStatus public property
     */
    public $registerStatus;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $centerName public property
     */
    public $centerName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $centerCode public property
     */
    public $centerCode;

    /**
     * @todo Write general description for this property
     * @var string|null $branchCount public property
     */
    public $branchCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $registrationNumber public property
     */
    public $registrationNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $freeUseGoldenPackExpireDate public property
     */
    public $freeUseGoldenPackExpireDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $cityId public property
     */
    public $cityId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $cashPayment public property
     */
    public $cashPayment;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $showInEasyBimeh public property
     */
    public $showInEasyBimeh;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $installmentsPayment public property
     */
    public $installmentsPayment;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isInitialApplicant public property
     */
    public $isInitialApplicant;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $branchsCount public property
     */
    public $branchsCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $employeesCount public property
     */
    public $employeesCount;

    /**
     * @todo Write general description for this property
     * @var string|null $zoneId public property
     */
    public $zoneId;

    /**
     * @todo Write general description for this property
     * @var string|null $smsChargingStock public property
     */
    public $smsChargingStock;

    /**
     * @todo Write general description for this property
     * @var string|null $independentBranch public property
     */
    public $independentBranch;

    /**
     * @todo Write general description for this property
     * @var string|null $disableReason public property
     */
    public $disableReason;

    /**
     * @todo Write general description for this property
     * @var string|null $termsConditions public property
     */
    public $termsConditions;

    /**
     * @todo Write general description for this property
     * @var string|null $disableReasonDescription public property
     */
    public $disableReasonDescription;

    /**
     * @todo Write general description for this property
     * @var string|null $unlimitedAccount public property
     */
    public $unlimitedAccount;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $whiteLabel public property
     */
    public $whiteLabel;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $phone public property
     */
    public $phone;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $fax public property
     */
    public $fax;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $address public property
     */
    public $address;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $zipCode public property
     */
    public $zipCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * @todo Write general description for this property
     * @var string|null $paymentUrl public property
     */
    public $paymentUrl;

    /**
     * @todo Write general description for this property
     * @var string|null $callbackUrl public property
     */
    public $callbackUrl;

    /**
     * @todo Write general description for this property
     * @var string|null $callbackUrlWhitelabel public property
     */
    public $callbackUrlWhitelabel;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $webSite public property
     */
    public $webSite;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $latitude public property
     */
    public $latitude;

    /**
     * @todo Write general description for this property
     * @required
     * @var double $longitude public property
     */
    public $longitude;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isActive public property
     */
    public $isActive;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @var string|null $cityRegionId public property
     */
    public $cityRegionId;

    /**
     * @todo Write general description for this property
     * @var string|null $provinceId public property
     */
    public $provinceId;

    /**
     * @todo Write general description for this property
     * @var string|null $cityName public property
     */
    public $cityName;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $metaMediaActivityLicenceId public property
     */
    public $metaMediaActivityLicenceId;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaActivityLicenceUrl public property
     */
    public $metaMediaActivityLicenceUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $insuranceCompanyId public property
     */
    public $insuranceCompanyId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $activePackageId public property
     */
    public $activePackageId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $packageActivationLastDate public property
     */
    public $packageActivationLastDate;

    /**
     * @todo Write general description for this property
     * @var string|null $licenseApiKey public property
     */
    public $licenseApiKey;

    /**
     * @todo Write general description for this property
     * @var string|null $verifyRequestUrl public property
     */
    public $verifyRequestUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $onlinePayment public property
     */
    public $onlinePayment;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $cardToCardPayment public property
     */
    public $cardToCardPayment;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $bankTransferPayment public property
     */
    public $bankTransferPayment;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $cashOnDelivery public property
     */
    public $cashOnDelivery;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $bankTransferSameOnlinePaymentInfo public property
     */
    public $bankTransferSameOnlinePaymentInfo;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $bankParamId public property
     */
    public $bankParamId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $accountOwner public property
     */
    public $accountOwner;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $accountNumber public property
     */
    public $accountNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $iban public property
     */
    public $iban;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $cardBankParamId public property
     */
    public $cardBankParamId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $cardAccountOwner public property
     */
    public $cardAccountOwner;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $cardAccountNumber public property
     */
    public $cardAccountNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $bankTransferParamId public property
     */
    public $bankTransferParamId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $bankTransferAccountOwner public property
     */
    public $bankTransferAccountOwner;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $bankTransferAccountNumber public property
     */
    public $bankTransferAccountNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $bankTransferIBAN public property
     */
    public $bankTransferIBAN;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                                Initialization value for $this->id
     * @param string  $personId                          Initialization value for $this->personId
     * @param integer $personalityType                   Initialization value for $this->personalityType
     * @param integer $insuranceCentreType               Initialization value for $this->insuranceCentreType
     * @param integer $registerStatus                    Initialization value for $this->registerStatus
     * @param string  $centerName                        Initialization value for $this->centerName
     * @param string  $centerCode                        Initialization value for $this->centerCode
     * @param string  $branchCount                       Initialization value for $this->branchCount
     * @param string  $registrationNumber                Initialization value for $this->registrationNumber
     * @param string  $freeUseGoldenPackExpireDate       Initialization value for $this->freeUseGoldenPackExpireDate
     * @param integer $cityId                            Initialization value for $this->cityId
     * @param bool    $cashPayment                       Initialization value for $this->cashPayment
     * @param bool    $showInEasyBimeh                   Initialization value for $this->showInEasyBimeh
     * @param bool    $installmentsPayment               Initialization value for $this->installmentsPayment
     * @param bool    $isInitialApplicant                Initialization value for $this->isInitialApplicant
     * @param integer $branchsCount                      Initialization value for $this->branchsCount
     * @param integer $employeesCount                    Initialization value for $this->employeesCount
     * @param string  $zoneId                            Initialization value for $this->zoneId
     * @param string  $smsChargingStock                  Initialization value for $this->smsChargingStock
     * @param string  $independentBranch                 Initialization value for $this->independentBranch
     * @param string  $disableReason                     Initialization value for $this->disableReason
     * @param string  $termsConditions                   Initialization value for $this->termsConditions
     * @param string  $disableReasonDescription          Initialization value for $this->disableReasonDescription
     * @param string  $unlimitedAccount                  Initialization value for $this->unlimitedAccount
     * @param bool    $whiteLabel                        Initialization value for $this->whiteLabel
     * @param string  $phone                             Initialization value for $this->phone
     * @param string  $fax                               Initialization value for $this->fax
     * @param string  $address                           Initialization value for $this->address
     * @param string  $zipCode                           Initialization value for $this->zipCode
     * @param string  $email                             Initialization value for $this->email
     * @param string  $paymentUrl                        Initialization value for $this->paymentUrl
     * @param string  $callbackUrl                       Initialization value for $this->callbackUrl
     * @param string  $callbackUrlWhitelabel             Initialization value for $this->callbackUrlWhitelabel
     * @param string  $webSite                           Initialization value for $this->webSite
     * @param double  $latitude                          Initialization value for $this->latitude
     * @param double  $longitude                         Initialization value for $this->longitude
     * @param bool    $isActive                          Initialization value for $this->isActive
     * @param string  $insuranceCentreId                 Initialization value for $this->insuranceCentreId
     * @param string  $cityRegionId                      Initialization value for $this->cityRegionId
     * @param string  $provinceId                        Initialization value for $this->provinceId
     * @param string  $cityName                          Initialization value for $this->cityName
     * @param integer $metaMediaActivityLicenceId        Initialization value for $this->metaMediaActivityLicenceId
     * @param string  $metaMediaActivityLicenceUrl       Initialization value for $this->metaMediaActivityLicenceUrl
     * @param string  $createOnPersianDate               Initialization value for $this->createOnPersianDate
     * @param array   $insuranceCompanyId                Initialization value for $this->insuranceCompanyId
     * @param integer $activePackageId                   Initialization value for $this->activePackageId
     * @param string  $packageActivationLastDate         Initialization value for $this->packageActivationLastDate
     * @param string  $licenseApiKey                     Initialization value for $this->licenseApiKey
     * @param string  $verifyRequestUrl                  Initialization value for $this->verifyRequestUrl
     * @param bool    $onlinePayment                     Initialization value for $this->onlinePayment
     * @param bool    $cardToCardPayment                 Initialization value for $this->cardToCardPayment
     * @param bool    $bankTransferPayment               Initialization value for $this->bankTransferPayment
     * @param bool    $cashOnDelivery                    Initialization value for $this->cashOnDelivery
     * @param bool    $bankTransferSameOnlinePaymentInfo Initialization value for $this-
     *                                                     >bankTransferSameOnlinePaymentInfo
     * @param integer $bankParamId                       Initialization value for $this->bankParamId
     * @param string  $accountOwner                      Initialization value for $this->accountOwner
     * @param string  $accountNumber                     Initialization value for $this->accountNumber
     * @param string  $iban                              Initialization value for $this->iban
     * @param integer $cardBankParamId                   Initialization value for $this->cardBankParamId
     * @param string  $cardAccountOwner                  Initialization value for $this->cardAccountOwner
     * @param string  $cardAccountNumber                 Initialization value for $this->cardAccountNumber
     * @param integer $bankTransferParamId               Initialization value for $this->bankTransferParamId
     * @param string  $bankTransferAccountOwner          Initialization value for $this->bankTransferAccountOwner
     * @param string  $bankTransferAccountNumber         Initialization value for $this->bankTransferAccountNumber
     * @param string  $bankTransferIBAN                  Initialization value for $this->bankTransferIBAN
     */
    public function __construct()
    {
        if (65 == func_num_args()) {
            $this->id                                = func_get_arg(0);
            $this->personId                          = func_get_arg(1);
            $this->personalityType                   = func_get_arg(2);
            $this->insuranceCentreType               = func_get_arg(3);
            $this->registerStatus                    = func_get_arg(4);
            $this->centerName                        = func_get_arg(5);
            $this->centerCode                        = func_get_arg(6);
            $this->branchCount                       = func_get_arg(7);
            $this->registrationNumber                = func_get_arg(8);
            $this->freeUseGoldenPackExpireDate       = func_get_arg(9);
            $this->cityId                            = func_get_arg(10);
            $this->cashPayment                       = func_get_arg(11);
            $this->showInEasyBimeh                   = func_get_arg(12);
            $this->installmentsPayment               = func_get_arg(13);
            $this->isInitialApplicant                = func_get_arg(14);
            $this->branchsCount                      = func_get_arg(15);
            $this->employeesCount                    = func_get_arg(16);
            $this->zoneId                            = func_get_arg(17);
            $this->smsChargingStock                  = func_get_arg(18);
            $this->independentBranch                 = func_get_arg(19);
            $this->disableReason                     = func_get_arg(20);
            $this->termsConditions                   = func_get_arg(21);
            $this->disableReasonDescription          = func_get_arg(22);
            $this->unlimitedAccount                  = func_get_arg(23);
            $this->whiteLabel                        = func_get_arg(24);
            $this->phone                             = func_get_arg(25);
            $this->fax                               = func_get_arg(26);
            $this->address                           = func_get_arg(27);
            $this->zipCode                           = func_get_arg(28);
            $this->email                             = func_get_arg(29);
            $this->paymentUrl                        = func_get_arg(30);
            $this->callbackUrl                       = func_get_arg(31);
            $this->callbackUrlWhitelabel             = func_get_arg(32);
            $this->webSite                           = func_get_arg(33);
            $this->latitude                          = func_get_arg(34);
            $this->longitude                         = func_get_arg(35);
            $this->isActive                          = func_get_arg(36);
            $this->insuranceCentreId                 = func_get_arg(37);
            $this->cityRegionId                      = func_get_arg(38);
            $this->provinceId                        = func_get_arg(39);
            $this->cityName                          = func_get_arg(40);
            $this->metaMediaActivityLicenceId        = func_get_arg(41);
            $this->metaMediaActivityLicenceUrl       = func_get_arg(42);
            $this->createOnPersianDate               = func_get_arg(43);
            $this->insuranceCompanyId                = func_get_arg(44);
            $this->activePackageId                   = func_get_arg(45);
            $this->packageActivationLastDate         = func_get_arg(46);
            $this->licenseApiKey                     = func_get_arg(47);
            $this->verifyRequestUrl                  = func_get_arg(48);
            $this->onlinePayment                     = func_get_arg(49);
            $this->cardToCardPayment                 = func_get_arg(50);
            $this->bankTransferPayment               = func_get_arg(51);
            $this->cashOnDelivery                    = func_get_arg(52);
            $this->bankTransferSameOnlinePaymentInfo = func_get_arg(53);
            $this->bankParamId                       = func_get_arg(54);
            $this->accountOwner                      = func_get_arg(55);
            $this->accountNumber                     = func_get_arg(56);
            $this->iban                              = func_get_arg(57);
            $this->cardBankParamId                   = func_get_arg(58);
            $this->cardAccountOwner                  = func_get_arg(59);
            $this->cardAccountNumber                 = func_get_arg(60);
            $this->bankTransferParamId               = func_get_arg(61);
            $this->bankTransferAccountOwner          = func_get_arg(62);
            $this->bankTransferAccountNumber         = func_get_arg(63);
            $this->bankTransferIBAN                  = func_get_arg(64);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                                = $this->id;
        $json['personId']                          = $this->personId;
        $json['personalityType']                   = $this->personalityType;
        $json['insuranceCentreType']               = $this->insuranceCentreType;
        $json['registerStatus']                    = $this->registerStatus;
        $json['centerName']                        = $this->centerName;
        $json['centerCode']                        = $this->centerCode;
        $json['branchCount']                       = $this->branchCount;
        $json['registrationNumber']                = $this->registrationNumber;
        $json['freeUseGoldenPackExpireDate']       = $this->freeUseGoldenPackExpireDate;
        $json['cityId']                            = $this->cityId;
        $json['cashPayment']                       = $this->cashPayment;
        $json['showInEasyBimeh']                   = $this->showInEasyBimeh;
        $json['installmentsPayment']               = $this->installmentsPayment;
        $json['isInitialApplicant']                = $this->isInitialApplicant;
        $json['branchsCount']                      = $this->branchsCount;
        $json['employeesCount']                    = $this->employeesCount;
        $json['zoneId']                            = $this->zoneId;
        $json['smsChargingStock']                  = $this->smsChargingStock;
        $json['independentBranch']                 = $this->independentBranch;
        $json['disableReason']                     = $this->disableReason;
        $json['termsConditions']                   = $this->termsConditions;
        $json['disableReasonDescription']          = $this->disableReasonDescription;
        $json['unlimitedAccount']                  = $this->unlimitedAccount;
        $json['whiteLabel']                        = $this->whiteLabel;
        $json['phone']                             = $this->phone;
        $json['fax']                               = $this->fax;
        $json['address']                           = $this->address;
        $json['zipCode']                           = $this->zipCode;
        $json['email']                             = $this->email;
        $json['paymentUrl']                        = $this->paymentUrl;
        $json['callbackUrl']                       = $this->callbackUrl;
        $json['callbackUrlWhitelabel']             = $this->callbackUrlWhitelabel;
        $json['webSite']                           = $this->webSite;
        $json['latitude']                          = $this->latitude;
        $json['longitude']                         = $this->longitude;
        $json['isActive']                          = $this->isActive;
        $json['insuranceCentreId']                 = $this->insuranceCentreId;
        $json['cityRegionId']                      = $this->cityRegionId;
        $json['provinceId']                        = $this->provinceId;
        $json['cityName']                          = $this->cityName;
        $json['metaMediaActivityLicenceId']        = $this->metaMediaActivityLicenceId;
        $json['metaMediaActivityLicenceUrl']       = $this->metaMediaActivityLicenceUrl;
        $json['createOnPersianDate']               = $this->createOnPersianDate;
        $json['insuranceCompanyId']                = $this->insuranceCompanyId;
        $json['activePackageId']                   = $this->activePackageId;
        $json['packageActivationLastDate']         = $this->packageActivationLastDate;
        $json['licenseApiKey']                     = $this->licenseApiKey;
        $json['verifyRequestUrl']                  = $this->verifyRequestUrl;
        $json['onlinePayment']                     = $this->onlinePayment;
        $json['cardToCardPayment']                 = $this->cardToCardPayment;
        $json['bankTransferPayment']               = $this->bankTransferPayment;
        $json['cashOnDelivery']                    = $this->cashOnDelivery;
        $json['bankTransferSameOnlinePaymentInfo'] = $this->bankTransferSameOnlinePaymentInfo;
        $json['bankParamId']                       = $this->bankParamId;
        $json['accountOwner']                      = $this->accountOwner;
        $json['accountNumber']                     = $this->accountNumber;
        $json['iban']                              = $this->iban;
        $json['cardBankParamId']                   = $this->cardBankParamId;
        $json['cardAccountOwner']                  = $this->cardAccountOwner;
        $json['cardAccountNumber']                 = $this->cardAccountNumber;
        $json['bankTransferParamId']               = $this->bankTransferParamId;
        $json['bankTransferAccountOwner']          = $this->bankTransferAccountOwner;
        $json['bankTransferAccountNumber']         = $this->bankTransferAccountNumber;
        $json['bankTransferIBAN']                  = $this->bankTransferIBAN;

        return $json;
    }
}
