<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class InsuranceDataFireInsurance implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insurancePolicyTypeVelue public property
     */
    public $insurancePolicyTypeVelue;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\FireInsurancePolicyExtendView $fireInsurancePolicyExtendView public property
     */
    public $fireInsurancePolicyExtendView;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\FireInsurancePolicyFilter $fireInsurancePolicyFilter public property
     */
    public $fireInsurancePolicyFilter;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $selectedInsurancePolicyHasBeenChanged public property
     */
    public $selectedInsurancePolicyHasBeenChanged;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isPaymented public property
     */
    public $isPaymented;

    /**
     * @todo Write general description for this property
     * @var string|null $payable public property
     */
    public $payable;

    /**
     * @todo Write general description for this property
     * @var string|null $paymented public property
     */
    public $paymented;

    /**
     * @todo Write general description for this property
     * @var string|null $conflict public property
     */
    public $conflict;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $hasConflictDocument public property
     */
    public $hasConflictDocument;

    /**
     * @todo Write general description for this property
     * @var string|null $initialPrice public property
     */
    public $initialPrice;

    /**
     * @todo Write general description for this property
     * @var string|null $finalPrice public property
     */
    public $finalPrice;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCompanyName public property
     */
    public $insuranceCompanyName;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreName public property
     */
    public $insuranceCentreName;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isInsuranceCentreAdmin public property
     */
    public $isInsuranceCentreAdmin;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $insurancePolicyPaymentDocuments public property
     */
    public $insurancePolicyPaymentDocuments;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePolicyConflict public property
     */
    public $insurancePolicyConflict;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePolicyCondition public property
     */
    public $insurancePolicyCondition;

    /**
     * @todo Write general description for this property
     * @var string|null $person public property
     */
    public $person;

    /**
     * @todo Write general description for this property
     * @var string|null $insurancePolicy public property
     */
    public $insurancePolicy;

    /**
     * @todo Write general description for this property
     * @var string|null $shoppingCard public property
     */
    public $shoppingCard;

    /**
     * @todo Write general description for this property
     * @var string|null $shoppingCardPostalPacket public property
     */
    public $shoppingCardPostalPacket;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer                       $insurancePolicyTypeVelue              Initialization value for $this-
     *                                                                               >insurancePolicyTypeVelue
     * @param FireInsurancePolicyExtendView $fireInsurancePolicyExtendView         Initialization value for $this-
     *                                                                               >fireInsurancePolicyExtendView
     * @param FireInsurancePolicyFilter     $fireInsurancePolicyFilter             Initialization value for $this-
     *                                                                               >fireInsurancePolicyFilter
     * @param integer                       $id                                    Initialization value for $this->id
     * @param bool                          $selectedInsurancePolicyHasBeenChanged Initialization value for $this-
     *                                                                               >selectedInsurancePolicyHasBeenChan
     *                                                                               ged
     * @param bool                          $isPaymented                           Initialization value for $this-
     *                                                                               >isPaymented
     * @param string                        $payable                               Initialization value for $this-
     *                                                                               >payable
     * @param string                        $paymented                             Initialization value for $this-
     *                                                                               >paymented
     * @param string                        $conflict                              Initialization value for $this-
     *                                                                               >conflict
     * @param bool                          $hasConflictDocument                   Initialization value for $this-
     *                                                                               >hasConflictDocument
     * @param string                        $initialPrice                          Initialization value for $this-
     *                                                                               >initialPrice
     * @param string                        $finalPrice                            Initialization value for $this-
     *                                                                               >finalPrice
     * @param string                        $insuranceCompanyName                  Initialization value for $this-
     *                                                                               >insuranceCompanyName
     * @param string                        $insuranceCentreName                   Initialization value for $this-
     *                                                                               >insuranceCentreName
     * @param bool                          $isInsuranceCentreAdmin                Initialization value for $this-
     *                                                                               >isInsuranceCentreAdmin
     * @param array                         $insurancePolicyPaymentDocuments       Initialization value for $this-
     *                                                                               >insurancePolicyPaymentDocuments
     * @param string                        $insurancePolicyConflict               Initialization value for $this-
     *                                                                               >insurancePolicyConflict
     * @param string                        $insurancePolicyCondition              Initialization value for $this-
     *                                                                               >insurancePolicyCondition
     * @param string                        $person                                Initialization value for $this-
     *                                                                               >person
     * @param string                        $insurancePolicy                       Initialization value for $this-
     *                                                                               >insurancePolicy
     * @param string                        $shoppingCard                          Initialization value for $this-
     *                                                                               >shoppingCard
     * @param string                        $shoppingCardPostalPacket              Initialization value for $this-
     *                                                                               >shoppingCardPostalPacket
     */
    public function __construct()
    {
        if (22 == func_num_args()) {
            $this->insurancePolicyTypeVelue              = func_get_arg(0);
            $this->fireInsurancePolicyExtendView         = func_get_arg(1);
            $this->fireInsurancePolicyFilter             = func_get_arg(2);
            $this->id                                    = func_get_arg(3);
            $this->selectedInsurancePolicyHasBeenChanged = func_get_arg(4);
            $this->isPaymented                           = func_get_arg(5);
            $this->payable                               = func_get_arg(6);
            $this->paymented                             = func_get_arg(7);
            $this->conflict                              = func_get_arg(8);
            $this->hasConflictDocument                   = func_get_arg(9);
            $this->initialPrice                          = func_get_arg(10);
            $this->finalPrice                            = func_get_arg(11);
            $this->insuranceCompanyName                  = func_get_arg(12);
            $this->insuranceCentreName                   = func_get_arg(13);
            $this->isInsuranceCentreAdmin                = func_get_arg(14);
            $this->insurancePolicyPaymentDocuments       = func_get_arg(15);
            $this->insurancePolicyConflict               = func_get_arg(16);
            $this->insurancePolicyCondition              = func_get_arg(17);
            $this->person                                = func_get_arg(18);
            $this->insurancePolicy                       = func_get_arg(19);
            $this->shoppingCard                          = func_get_arg(20);
            $this->shoppingCardPostalPacket              = func_get_arg(21);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['insurancePolicyTypeVelue']              = $this->insurancePolicyTypeVelue;
        $json['fireInsurancePolicyExtendView']         = $this->fireInsurancePolicyExtendView;
        $json['fireInsurancePolicyFilter']             = $this->fireInsurancePolicyFilter;
        $json['id']                                    = $this->id;
        $json['selectedInsurancePolicyHasBeenChanged'] = $this->selectedInsurancePolicyHasBeenChanged;
        $json['isPaymented']                           = $this->isPaymented;
        $json['payable']                               = $this->payable;
        $json['paymented']                             = $this->paymented;
        $json['conflict']                              = $this->conflict;
        $json['hasConflictDocument']                   = $this->hasConflictDocument;
        $json['initialPrice']                          = $this->initialPrice;
        $json['finalPrice']                            = $this->finalPrice;
        $json['insuranceCompanyName']                  = $this->insuranceCompanyName;
        $json['insuranceCentreName']                   = $this->insuranceCentreName;
        $json['isInsuranceCentreAdmin']                = $this->isInsuranceCentreAdmin;
        $json['insurancePolicyPaymentDocuments']       = $this->insurancePolicyPaymentDocuments;
        $json['insurancePolicyConflict']               = $this->insurancePolicyConflict;
        $json['insurancePolicyCondition']              = $this->insurancePolicyCondition;
        $json['person']                                = $this->person;
        $json['insurancePolicy']                       = $this->insurancePolicy;
        $json['shoppingCard']                          = $this->shoppingCard;
        $json['shoppingCardPostalPacket']              = $this->shoppingCardPostalPacket;

        return $json;
    }
}
