<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class InsuranceCentrePortal implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $centreName public property
     */
    public $centreName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $subDomainName public property
     */
    public $subDomainName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $subTitle public property
     */
    public $subTitle;

    /**
     * @todo Write general description for this property
     * @var string|null $contactUs public property
     */
    public $contactUs;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $aboutUs public property
     */
    public $aboutUs;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $ourService public property
     */
    public $ourService;

    /**
     * @todo Write general description for this property
     * @var string|null $termsConditions public property
     */
    public $termsConditions;

    /**
     * @todo Write general description for this property
     * @var string|null $copyright public property
     */
    public $copyright;

    /**
     * @todo Write general description for this property
     * @var string|null $headerTitle public property
     */
    public $headerTitle;

    /**
     * @todo Write general description for this property
     * @var string|null $headerBody public property
     */
    public $headerBody;

    /**
     * @todo Write general description for this property
     * @var string|null $footerColor public property
     */
    public $footerColor;

    /**
     * @todo Write general description for this property
     * @var string|null $backgroundColor public property
     */
    public $backgroundColor;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $licensed public property
     */
    public $licensed;

    /**
     * @todo Write general description for this property
     * @var string|null $defaultLogo public property
     */
    public $defaultLogo;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $titleColor public property
     */
    public $titleColor;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $subTitleColor public property
     */
    public $subTitleColor;

    /**
     * @todo Write general description for this property
     * @var string|null $eTrustSymbol public property
     */
    public $eTrustSymbol;

    /**
     * @todo Write general description for this property
     * @var string|null $digitalMediaOrganizerSymbol public property
     */
    public $digitalMediaOrganizerSymbol;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $googlePlus public property
     */
    public $googlePlus;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $telegram public property
     */
    public $telegram;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $instagram public property
     */
    public $instagram;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $faceBook public property
     */
    public $faceBook;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $twitter public property
     */
    public $twitter;

    /**
     * @todo Write general description for this property
     * @var string|null $saturdayToWednesdayFromHour public property
     */
    public $saturdayToWednesdayFromHour;

    /**
     * @todo Write general description for this property
     * @var string|null $saturdayToWednesdayToHour public property
     */
    public $saturdayToWednesdayToHour;

    /**
     * @todo Write general description for this property
     * @var string|null $thursdayFromHour public property
     */
    public $thursdayFromHour;

    /**
     * @todo Write general description for this property
     * @var string|null $thursdayToHour public property
     */
    public $thursdayToHour;

    /**
     * @todo Write general description for this property
     * @var string|null $fridayFromHour public property
     */
    public $fridayFromHour;

    /**
     * @todo Write general description for this property
     * @var string|null $fridayToHour public property
     */
    public $fridayToHour;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $metaMediaFileHeaderId public property
     */
    public $metaMediaFileHeaderId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $metaMediaFileHeaderUrl public property
     */
    public $metaMediaFileHeaderUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $metaMediaFileLogoId public property
     */
    public $metaMediaFileLogoId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $metaMediaFileLogoUrl public property
     */
    public $metaMediaFileLogoUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $metaMediaFileFaviconId public property
     */
    public $metaMediaFileFaviconId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $metaMediaFileFaviconUrl public property
     */
    public $metaMediaFileFaviconUrl;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaFileFooterId public property
     */
    public $metaMediaFileFooterId;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaFileFooterUrl public property
     */
    public $metaMediaFileFooterUrl;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $insuranceCentreId           Initialization value for $this->insuranceCentreId
     * @param string  $centreName                  Initialization value for $this->centreName
     * @param string  $subDomainName               Initialization value for $this->subDomainName
     * @param string  $title                       Initialization value for $this->title
     * @param string  $subTitle                    Initialization value for $this->subTitle
     * @param string  $contactUs                   Initialization value for $this->contactUs
     * @param string  $aboutUs                     Initialization value for $this->aboutUs
     * @param string  $ourService                  Initialization value for $this->ourService
     * @param string  $termsConditions             Initialization value for $this->termsConditions
     * @param string  $copyright                   Initialization value for $this->copyright
     * @param string  $headerTitle                 Initialization value for $this->headerTitle
     * @param string  $headerBody                  Initialization value for $this->headerBody
     * @param string  $footerColor                 Initialization value for $this->footerColor
     * @param string  $backgroundColor             Initialization value for $this->backgroundColor
     * @param bool    $licensed                    Initialization value for $this->licensed
     * @param string  $defaultLogo                 Initialization value for $this->defaultLogo
     * @param string  $titleColor                  Initialization value for $this->titleColor
     * @param string  $subTitleColor               Initialization value for $this->subTitleColor
     * @param string  $eTrustSymbol                Initialization value for $this->eTrustSymbol
     * @param string  $digitalMediaOrganizerSymbol Initialization value for $this->digitalMediaOrganizerSymbol
     * @param string  $googlePlus                  Initialization value for $this->googlePlus
     * @param string  $telegram                    Initialization value for $this->telegram
     * @param string  $instagram                   Initialization value for $this->instagram
     * @param string  $faceBook                    Initialization value for $this->faceBook
     * @param string  $twitter                     Initialization value for $this->twitter
     * @param string  $saturdayToWednesdayFromHour Initialization value for $this->saturdayToWednesdayFromHour
     * @param string  $saturdayToWednesdayToHour   Initialization value for $this->saturdayToWednesdayToHour
     * @param string  $thursdayFromHour            Initialization value for $this->thursdayFromHour
     * @param string  $thursdayToHour              Initialization value for $this->thursdayToHour
     * @param string  $fridayFromHour              Initialization value for $this->fridayFromHour
     * @param string  $fridayToHour                Initialization value for $this->fridayToHour
     * @param integer $metaMediaFileHeaderId       Initialization value for $this->metaMediaFileHeaderId
     * @param string  $metaMediaFileHeaderUrl      Initialization value for $this->metaMediaFileHeaderUrl
     * @param integer $metaMediaFileLogoId         Initialization value for $this->metaMediaFileLogoId
     * @param string  $metaMediaFileLogoUrl        Initialization value for $this->metaMediaFileLogoUrl
     * @param integer $metaMediaFileFaviconId      Initialization value for $this->metaMediaFileFaviconId
     * @param string  $metaMediaFileFaviconUrl     Initialization value for $this->metaMediaFileFaviconUrl
     * @param string  $metaMediaFileFooterId       Initialization value for $this->metaMediaFileFooterId
     * @param string  $metaMediaFileFooterUrl      Initialization value for $this->metaMediaFileFooterUrl
     */
    public function __construct()
    {
        if (39 == func_num_args()) {
            $this->insuranceCentreId           = func_get_arg(0);
            $this->centreName                  = func_get_arg(1);
            $this->subDomainName               = func_get_arg(2);
            $this->title                       = func_get_arg(3);
            $this->subTitle                    = func_get_arg(4);
            $this->contactUs                   = func_get_arg(5);
            $this->aboutUs                     = func_get_arg(6);
            $this->ourService                  = func_get_arg(7);
            $this->termsConditions             = func_get_arg(8);
            $this->copyright                   = func_get_arg(9);
            $this->headerTitle                 = func_get_arg(10);
            $this->headerBody                  = func_get_arg(11);
            $this->footerColor                 = func_get_arg(12);
            $this->backgroundColor             = func_get_arg(13);
            $this->licensed                    = func_get_arg(14);
            $this->defaultLogo                 = func_get_arg(15);
            $this->titleColor                  = func_get_arg(16);
            $this->subTitleColor               = func_get_arg(17);
            $this->eTrustSymbol                = func_get_arg(18);
            $this->digitalMediaOrganizerSymbol = func_get_arg(19);
            $this->googlePlus                  = func_get_arg(20);
            $this->telegram                    = func_get_arg(21);
            $this->instagram                   = func_get_arg(22);
            $this->faceBook                    = func_get_arg(23);
            $this->twitter                     = func_get_arg(24);
            $this->saturdayToWednesdayFromHour = func_get_arg(25);
            $this->saturdayToWednesdayToHour   = func_get_arg(26);
            $this->thursdayFromHour            = func_get_arg(27);
            $this->thursdayToHour              = func_get_arg(28);
            $this->fridayFromHour              = func_get_arg(29);
            $this->fridayToHour                = func_get_arg(30);
            $this->metaMediaFileHeaderId       = func_get_arg(31);
            $this->metaMediaFileHeaderUrl      = func_get_arg(32);
            $this->metaMediaFileLogoId         = func_get_arg(33);
            $this->metaMediaFileLogoUrl        = func_get_arg(34);
            $this->metaMediaFileFaviconId      = func_get_arg(35);
            $this->metaMediaFileFaviconUrl     = func_get_arg(36);
            $this->metaMediaFileFooterId       = func_get_arg(37);
            $this->metaMediaFileFooterUrl      = func_get_arg(38);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['insuranceCentreId']           = $this->insuranceCentreId;
        $json['centreName']                  = $this->centreName;
        $json['subDomainName']               = $this->subDomainName;
        $json['title']                       = $this->title;
        $json['subTitle']                    = $this->subTitle;
        $json['contactUs']                   = $this->contactUs;
        $json['aboutUs']                     = $this->aboutUs;
        $json['ourService']                  = $this->ourService;
        $json['termsConditions']             = $this->termsConditions;
        $json['copyright']                   = $this->copyright;
        $json['headerTitle']                 = $this->headerTitle;
        $json['headerBody']                  = $this->headerBody;
        $json['footerColor']                 = $this->footerColor;
        $json['backgroundColor']             = $this->backgroundColor;
        $json['licensed']                    = $this->licensed;
        $json['defaultLogo']                 = $this->defaultLogo;
        $json['titleColor']                  = $this->titleColor;
        $json['subTitleColor']               = $this->subTitleColor;
        $json['eTrustSymbol']                = $this->eTrustSymbol;
        $json['digitalMediaOrganizerSymbol'] = $this->digitalMediaOrganizerSymbol;
        $json['googlePlus']                  = $this->googlePlus;
        $json['telegram']                    = $this->telegram;
        $json['instagram']                   = $this->instagram;
        $json['faceBook']                    = $this->faceBook;
        $json['twitter']                     = $this->twitter;
        $json['saturdayToWednesdayFromHour'] = $this->saturdayToWednesdayFromHour;
        $json['saturdayToWednesdayToHour']   = $this->saturdayToWednesdayToHour;
        $json['thursdayFromHour']            = $this->thursdayFromHour;
        $json['thursdayToHour']              = $this->thursdayToHour;
        $json['fridayFromHour']              = $this->fridayFromHour;
        $json['fridayToHour']                = $this->fridayToHour;
        $json['metaMediaFileHeaderId']       = $this->metaMediaFileHeaderId;
        $json['metaMediaFileHeaderUrl']      = $this->metaMediaFileHeaderUrl;
        $json['metaMediaFileLogoId']         = $this->metaMediaFileLogoId;
        $json['metaMediaFileLogoUrl']        = $this->metaMediaFileLogoUrl;
        $json['metaMediaFileFaviconId']      = $this->metaMediaFileFaviconId;
        $json['metaMediaFileFaviconUrl']     = $this->metaMediaFileFaviconUrl;
        $json['metaMediaFileFooterId']       = $this->metaMediaFileFooterId;
        $json['metaMediaFileFooterUrl']      = $this->metaMediaFileFooterUrl;

        return $json;
    }
}
