<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class InsuranceExtraCoverageExtraData implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $defaultStatus public property
     */
    public $defaultStatus;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $requiringExpertVisit public property
     */
    public $requiringExpertVisit;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool $defaultStatus        Initialization value for $this->defaultStatus
     * @param bool $requiringExpertVisit Initialization value for $this->requiringExpertVisit
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->defaultStatus        = func_get_arg(0);
            $this->requiringExpertVisit = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['defaultStatus']        = $this->defaultStatus;
        $json['requiringExpertVisit'] = $this->requiringExpertVisit;

        return $json;
    }
}
