<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class InsurancePolicyTracking implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $aliasName public property
     */
    public $aliasName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $centerName public property
     */
    public $centerName;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insurancePolicyType public property
     */
    public $insurancePolicyType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $insuranceType public property
     */
    public $insuranceType;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $price public property
     */
    public $price;

    /**
     * @todo Write general description for this property
     * @var string|null $paymented public property
     */
    public $paymented;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                  Initialization value for $this->id
     * @param string  $aliasName           Initialization value for $this->aliasName
     * @param string  $status              Initialization value for $this->status
     * @param string  $createOnPersianDate Initialization value for $this->createOnPersianDate
     * @param string  $centerName          Initialization value for $this->centerName
     * @param integer $insurancePolicyType Initialization value for $this->insurancePolicyType
     * @param string  $insuranceType       Initialization value for $this->insuranceType
     * @param integer $price               Initialization value for $this->price
     * @param string  $paymented           Initialization value for $this->paymented
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->id                  = func_get_arg(0);
            $this->aliasName           = func_get_arg(1);
            $this->status              = func_get_arg(2);
            $this->createOnPersianDate = func_get_arg(3);
            $this->centerName          = func_get_arg(4);
            $this->insurancePolicyType = func_get_arg(5);
            $this->insuranceType       = func_get_arg(6);
            $this->price               = func_get_arg(7);
            $this->paymented           = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                  = $this->id;
        $json['aliasName']           = $this->aliasName;
        $json['status']              = $this->status;
        $json['createOnPersianDate'] = $this->createOnPersianDate;
        $json['centerName']          = $this->centerName;
        $json['insurancePolicyType'] = $this->insurancePolicyType;
        $json['insuranceType']       = $this->insuranceType;
        $json['price']               = $this->price;
        $json['paymented']           = $this->paymented;

        return $json;
    }
}
