<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LiabilityDoctorInsurancePolicyExtendView implements JsonSerializable
{
    /**
     * شناسه ی نرخ پوشش پزشکی
     * @var string|null $liabilityDoctorCoverageRateId public property
     */
    public $liabilityDoctorCoverageRateId;

    /**
     * شناسه ی دوره های فعالیت
     * @var string|null $activityAreaParamId public property
     */
    public $activityAreaParamId;

    /**
     * شاسه ی تخصص
     * @var string|null $expertiseParamId public property
     */
    public $expertiseParamId;

    /**
     * شناسه ی سقف تعهد
     * @var string|null $commitmentCeilingParamId public property
     */
    public $commitmentCeilingParamId;

    /**
     * شناسه ی تخفیف
     * @var string|null $insuranceRiskLevelId public property
     */
    public $insuranceRiskLevelId;

    /**
     * تاریخ پایان بیمه نامه
     * @var string|null $currentInsuranceDeadline public property
     */
    public $currentInsuranceDeadline;

    /**
     * نرخ تخفیف پوشش
     * @var string|null $riskLevelDiscountRate public property
     */
    public $riskLevelDiscountRate;

    /**
     * خسارت جانی
     * @var string|null $physicalCommitment public property
     */
    public $physicalCommitment;

    /**
     * نرخ تخفیف
     * @var string|null $discountRate public property
     */
    public $discountRate;

    /**
     * پوشش پایه
     * @var string|null $basePremium public property
     */
    public $basePremium;

    /**
     * پوشش ها
     * @var string|null $allPremium public property
     */
    public $allPremium;

    /**
     * اطلاعات اضافه
     * @var string|null $allExtraValues public property
     */
    public $allExtraValues;

    /**
     * نرخ تخفیف شرکت بیمه
     * @required
     * @var integer $insuranceCompanyDiscountRate public property
     */
    public $insuranceCompanyDiscountRate;

    /**
     * لیست تخفیفات
     * @required
     * @var integer $allDiscount public property
     */
    public $allDiscount;

    /**
     * نوع ارز حق بیمه
     * @required
     * @var integer $exchangePremium public property
     */
    public $exchangePremium;

    /**
     * نام پزشک
     * @var string|null $doctorName public property
     */
    public $doctorName;

    /**
     * شماره ی نظام پزشکی
     * @var string|null $medicalSystemNO public property
     */
    public $medicalSystemNO;

    /**
     * آدرس
     * @var string|null $address public property
     */
    public $address;

    /**
     * آیا رزیدنت است؟
     * @required
     * @var bool $isResident public property
     */
    public $isResident;

    /**
     * آیا دانشجو است؟
     * @required
     * @var bool $isStudent public property
     */
    public $isStudent;

    /**
     * دارای مطب؟
     * @var string|null $hasClinic public property
     */
    public $hasClinic;

    /**
     * شناسه ی گواهی نظام پزشکی
     * @var string|null $metaMediaMedicalSystemLicenseId public property
     */
    public $metaMediaMedicalSystemLicenseId;

    /**
     * آدرس گواهی نظام پزشکی
     * @var string|null $metaMediaMedicalSystemLicenseUrl public property
     */
    public $metaMediaMedicalSystemLicenseUrl;

    /**
     * شناسه ی کارت ملی
     * @var string|null $metaMediaNationalCardId public property
     */
    public $metaMediaNationalCardId;

    /**
     * آدرس کارت ملی
     * @var string|null $metaMediaNationalCardUrl public property
     */
    public $metaMediaNationalCardUrl;

    /**
     * شناسه ی بیمه نامه ی کنونی
     * @var string|null $metaMediaCurrentInsurancePolicyId public property
     */
    public $metaMediaCurrentInsurancePolicyId;

    /**
     * آدرس بیمه نامه ی کنونی
     * @var string|null $metaMediaCurrentInsurancePolicyUrl public property
     */
    public $metaMediaCurrentInsurancePolicyUrl;

    /**
     * شناسه ی دوره های بیمه نامه
     * @var string|null $activityAreaEnumName public property
     */
    public $activityAreaEnumName;

    /**
     * نام دوره ی بیمه نامه
     * @var string|null $activityAreaTitle public property
     */
    public $activityAreaTitle;

    /**
     * نام تخصص
     * @var string|null $expertiseTitle public property
     */
    public $expertiseTitle;

    /**
     * وضعیت پزشک
     * @var string|null $docterStatusTitle public property
     */
    public $docterStatusTitle;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $liabilityDoctorCoverageRateId      Initialization value for $this-
     *                                                      >liabilityDoctorCoverageRateId
     * @param string  $activityAreaParamId                Initialization value for $this->activityAreaParamId
     * @param string  $expertiseParamId                   Initialization value for $this->expertiseParamId
     * @param string  $commitmentCeilingParamId           Initialization value for $this->commitmentCeilingParamId
     * @param string  $insuranceRiskLevelId               Initialization value for $this->insuranceRiskLevelId
     * @param string  $currentInsuranceDeadline           Initialization value for $this->currentInsuranceDeadline
     * @param string  $riskLevelDiscountRate              Initialization value for $this->riskLevelDiscountRate
     * @param string  $physicalCommitment                 Initialization value for $this->physicalCommitment
     * @param string  $discountRate                       Initialization value for $this->discountRate
     * @param string  $basePremium                        Initialization value for $this->basePremium
     * @param string  $allPremium                         Initialization value for $this->allPremium
     * @param string  $allExtraValues                     Initialization value for $this->allExtraValues
     * @param integer $insuranceCompanyDiscountRate       Initialization value for $this-
     *                                                      >insuranceCompanyDiscountRate
     * @param integer $allDiscount                        Initialization value for $this->allDiscount
     * @param integer $exchangePremium                    Initialization value for $this->exchangePremium
     * @param string  $doctorName                         Initialization value for $this->doctorName
     * @param string  $medicalSystemNO                    Initialization value for $this->medicalSystemNO
     * @param string  $address                            Initialization value for $this->address
     * @param bool    $isResident                         Initialization value for $this->isResident
     * @param bool    $isStudent                          Initialization value for $this->isStudent
     * @param string  $hasClinic                          Initialization value for $this->hasClinic
     * @param string  $metaMediaMedicalSystemLicenseId    Initialization value for $this-
     *                                                      >metaMediaMedicalSystemLicenseId
     * @param string  $metaMediaMedicalSystemLicenseUrl   Initialization value for $this-
     *                                                      >metaMediaMedicalSystemLicenseUrl
     * @param string  $metaMediaNationalCardId            Initialization value for $this->metaMediaNationalCardId
     * @param string  $metaMediaNationalCardUrl           Initialization value for $this->metaMediaNationalCardUrl
     * @param string  $metaMediaCurrentInsurancePolicyId  Initialization value for $this-
     *                                                      >metaMediaCurrentInsurancePolicyId
     * @param string  $metaMediaCurrentInsurancePolicyUrl Initialization value for $this-
     *                                                      >metaMediaCurrentInsurancePolicyUrl
     * @param string  $activityAreaEnumName               Initialization value for $this->activityAreaEnumName
     * @param string  $activityAreaTitle                  Initialization value for $this->activityAreaTitle
     * @param string  $expertiseTitle                     Initialization value for $this->expertiseTitle
     * @param string  $docterStatusTitle                  Initialization value for $this->docterStatusTitle
     */
    public function __construct()
    {
        if (31 == func_num_args()) {
            $this->liabilityDoctorCoverageRateId      = func_get_arg(0);
            $this->activityAreaParamId                = func_get_arg(1);
            $this->expertiseParamId                   = func_get_arg(2);
            $this->commitmentCeilingParamId           = func_get_arg(3);
            $this->insuranceRiskLevelId               = func_get_arg(4);
            $this->currentInsuranceDeadline           = func_get_arg(5);
            $this->riskLevelDiscountRate              = func_get_arg(6);
            $this->physicalCommitment                 = func_get_arg(7);
            $this->discountRate                       = func_get_arg(8);
            $this->basePremium                        = func_get_arg(9);
            $this->allPremium                         = func_get_arg(10);
            $this->allExtraValues                     = func_get_arg(11);
            $this->insuranceCompanyDiscountRate       = func_get_arg(12);
            $this->allDiscount                        = func_get_arg(13);
            $this->exchangePremium                    = func_get_arg(14);
            $this->doctorName                         = func_get_arg(15);
            $this->medicalSystemNO                    = func_get_arg(16);
            $this->address                            = func_get_arg(17);
            $this->isResident                         = func_get_arg(18);
            $this->isStudent                          = func_get_arg(19);
            $this->hasClinic                          = func_get_arg(20);
            $this->metaMediaMedicalSystemLicenseId    = func_get_arg(21);
            $this->metaMediaMedicalSystemLicenseUrl   = func_get_arg(22);
            $this->metaMediaNationalCardId            = func_get_arg(23);
            $this->metaMediaNationalCardUrl           = func_get_arg(24);
            $this->metaMediaCurrentInsurancePolicyId  = func_get_arg(25);
            $this->metaMediaCurrentInsurancePolicyUrl = func_get_arg(26);
            $this->activityAreaEnumName               = func_get_arg(27);
            $this->activityAreaTitle                  = func_get_arg(28);
            $this->expertiseTitle                     = func_get_arg(29);
            $this->docterStatusTitle                  = func_get_arg(30);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['liabilityDoctorCoverageRateId']      = $this->liabilityDoctorCoverageRateId;
        $json['activityAreaParamId']                = $this->activityAreaParamId;
        $json['expertiseParamId']                   = $this->expertiseParamId;
        $json['commitmentCeilingParamId']           = $this->commitmentCeilingParamId;
        $json['insuranceRiskLevelId']               = $this->insuranceRiskLevelId;
        $json['currentInsuranceDeadline']           = $this->currentInsuranceDeadline;
        $json['riskLevelDiscountRate']              = $this->riskLevelDiscountRate;
        $json['physicalCommitment']                 = $this->physicalCommitment;
        $json['discountRate']                       = $this->discountRate;
        $json['basePremium']                        = $this->basePremium;
        $json['allPremium']                         = $this->allPremium;
        $json['allExtraValues']                     = $this->allExtraValues;
        $json['insuranceCompanyDiscountRate']       = $this->insuranceCompanyDiscountRate;
        $json['allDiscount']                        = $this->allDiscount;
        $json['exchangePremium']                    = $this->exchangePremium;
        $json['doctorName']                         = $this->doctorName;
        $json['medicalSystemNO']                    = $this->medicalSystemNO;
        $json['address']                            = $this->address;
        $json['isResident']                         = $this->isResident;
        $json['isStudent']                          = $this->isStudent;
        $json['hasClinic']                          = $this->hasClinic;
        $json['metaMediaMedicalSystemLicenseId']    = $this->metaMediaMedicalSystemLicenseId;
        $json['metaMediaMedicalSystemLicenseUrl']   = $this->metaMediaMedicalSystemLicenseUrl;
        $json['metaMediaNationalCardId']            = $this->metaMediaNationalCardId;
        $json['metaMediaNationalCardUrl']           = $this->metaMediaNationalCardUrl;
        $json['metaMediaCurrentInsurancePolicyId']  = $this->metaMediaCurrentInsurancePolicyId;
        $json['metaMediaCurrentInsurancePolicyUrl'] = $this->metaMediaCurrentInsurancePolicyUrl;
        $json['activityAreaEnumName']               = $this->activityAreaEnumName;
        $json['activityAreaTitle']                  = $this->activityAreaTitle;
        $json['expertiseTitle']                     = $this->expertiseTitle;
        $json['docterStatusTitle']                  = $this->docterStatusTitle;

        return $json;
    }
}
