<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 *مدل اصلی بیمه ی مسئولیت پزشکان
 */
class LiabilityDoctorInsurance implements JsonSerializable
{
    /**
     * آیا طرح بیمه ای فعالی دارد؟
     * @required
     * @var bool $hasPlan public property
     */
    public $hasPlan;

    /**
     * حوزه ی فعالیت
     * @required
     * @var \EasyBimehLandingLib\Models\ActivityArea[] $activityArea public property
     */
    public $activityArea;

    /**
     * لیست تخصص ها
     * @required
     * @var \EasyBimehLandingLib\Models\Expertise[] $expertises public property
     */
    public $expertises;

    /**
     * لیست سقف تعهد
     * @required
     * @var \EasyBimehLandingLib\Models\CommitmentCeiling[] $commitmentCeilings public property
     */
    public $commitmentCeilings;

    /**
     * مبلغ تعهد
     * @required
     * @var integer $physicalCommitment public property
     */
    public $physicalCommitment;

    /**
     * لیست شرکت های بیمه
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceCompany[] $insuranceCompanies public property
     */
    public $insuranceCompanies;

    /**
     * تخفیف های بیمه ای
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceRiskLevel[] $insuranceRiskLevels public property
     */
    public $insuranceRiskLevels;

    /**
     * دوره های بیمه ای
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyTerm[] $insurancePolicyTerms public property
     */
    public $insurancePolicyTerms;

    /**
     * لیست استان ها
     * @required
     * @var \EasyBimehLandingLib\Models\Province[] $provinces public property
     */
    public $provinces;

    /**
     * لیست شهر ها
     * @required
     * @var array $cities public property
     */
    public $cities;

    /**
     * لیست مناطق شهر
     * @required
     * @var array $cityRegions public property
     */
    public $cityRegions;

    /**
     * نحوه ی ارسال
     * @required
     * @var \EasyBimehLandingLib\Models\ShippingType[] $shippingTypes public property
     */
    public $shippingTypes;

    /**
     * روش های پستی
     * @required
     * @var \EasyBimehLandingLib\Models\PostType[] $postTypes public property
     */
    public $postTypes;

    /**
     * شرایط بیمه نامه
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyCondition $insurancePolicyCondition public property
     */
    public $insurancePolicyCondition;

    /**
     * اطلاعات بیمه نامه
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceDataLiabilityDoctorInsurance $insuranceData public property
     */
    public $insuranceData;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool                                  $hasPlan                  Initialization value for $this->hasPlan
     * @param array                                 $activityArea             Initialization value for $this-
     *                                                                          >activityArea
     * @param array                                 $expertises               Initialization value for $this-
     *                                                                          >expertises
     * @param array                                 $commitmentCeilings       Initialization value for $this-
     *                                                                          >commitmentCeilings
     * @param integer                               $physicalCommitment       Initialization value for $this-
     *                                                                          >physicalCommitment
     * @param array                                 $insuranceCompanies       Initialization value for $this-
     *                                                                          >insuranceCompanies
     * @param array                                 $insuranceRiskLevels      Initialization value for $this-
     *                                                                          >insuranceRiskLevels
     * @param array                                 $insurancePolicyTerms     Initialization value for $this-
     *                                                                          >insurancePolicyTerms
     * @param array                                 $provinces                Initialization value for $this-
     *                                                                          >provinces
     * @param array                                 $cities                   Initialization value for $this->cities
     * @param array                                 $cityRegions              Initialization value for $this-
     *                                                                          >cityRegions
     * @param array                                 $shippingTypes            Initialization value for $this-
     *                                                                          >shippingTypes
     * @param array                                 $postTypes                Initialization value for $this-
     *                                                                          >postTypes
     * @param InsurancePolicyCondition              $insurancePolicyCondition Initialization value for $this-
     *                                                                          >insurancePolicyCondition
     * @param InsuranceDataLiabilityDoctorInsurance $insuranceData            Initialization value for $this-
     *                                                                          >insuranceData
     */
    public function __construct()
    {
        if (15 == func_num_args()) {
            $this->hasPlan                  = func_get_arg(0);
            $this->activityArea             = func_get_arg(1);
            $this->expertises               = func_get_arg(2);
            $this->commitmentCeilings       = func_get_arg(3);
            $this->physicalCommitment       = func_get_arg(4);
            $this->insuranceCompanies       = func_get_arg(5);
            $this->insuranceRiskLevels      = func_get_arg(6);
            $this->insurancePolicyTerms     = func_get_arg(7);
            $this->provinces                = func_get_arg(8);
            $this->cities                   = func_get_arg(9);
            $this->cityRegions              = func_get_arg(10);
            $this->shippingTypes            = func_get_arg(11);
            $this->postTypes                = func_get_arg(12);
            $this->insurancePolicyCondition = func_get_arg(13);
            $this->insuranceData            = func_get_arg(14);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['hasPlan']                  = $this->hasPlan;
        $json['activityArea']             = $this->activityArea;
        $json['expertises']               = $this->expertises;
        $json['commitmentCeilings']       = $this->commitmentCeilings;
        $json['physicalCommitment']       = $this->physicalCommitment;
        $json['insuranceCompanies']       = $this->insuranceCompanies;
        $json['insuranceRiskLevels']      = $this->insuranceRiskLevels;
        $json['insurancePolicyTerms']     = $this->insurancePolicyTerms;
        $json['provinces']                = $this->provinces;
        $json['cities']                   = $this->cities;
        $json['cityRegions']              = $this->cityRegions;
        $json['shippingTypes']            = $this->shippingTypes;
        $json['postTypes']                = $this->postTypes;
        $json['insurancePolicyCondition'] = $this->insurancePolicyCondition;
        $json['insuranceData']            = $this->insuranceData;

        return $json;
    }
}
