<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class LiabilityDoctorInsurancePolicyFilter implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $expertiseParamId public property
     */
    public $expertiseParamId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isResident public property
     */
    public $isResident;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isStudent public property
     */
    public $isStudent;

    /**
     * @todo Write general description for this property
     * @var string|null $riskLevelId public property
     */
    public $riskLevelId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $activityAreaParamId public property
     */
    public $activityAreaParamId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $commitmentCeilingParamId public property
     */
    public $commitmentCeilingParamId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceExtraCoverageIds public property
     */
    public $insuranceExtraCoverageIds;

    /**
     * @todo Write general description for this property
     * @var string|null $policyTermId public property
     */
    public $policyTermId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreSubDomainName public property
     */
    public $insuranceCentreSubDomainName;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCompanyId public property
     */
    public $insuranceCompanyId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isSearchQuery public property
     */
    public $isSearchQuery;

    /**
     * @todo Write general description for this property
     * @var string|null $giftCode public property
     */
    public $giftCode;

    /**
     * @todo Write general description for this property
     * @var string|null $customerUserId public property
     */
    public $customerUserId;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $expertiseParamId             Initialization value for $this->expertiseParamId
     * @param bool    $isResident                   Initialization value for $this->isResident
     * @param bool    $isStudent                    Initialization value for $this->isStudent
     * @param string  $riskLevelId                  Initialization value for $this->riskLevelId
     * @param integer $activityAreaParamId          Initialization value for $this->activityAreaParamId
     * @param integer $commitmentCeilingParamId     Initialization value for $this->commitmentCeilingParamId
     * @param string  $insuranceExtraCoverageIds    Initialization value for $this->insuranceExtraCoverageIds
     * @param string  $policyTermId                 Initialization value for $this->policyTermId
     * @param string  $insuranceCentreSubDomainName Initialization value for $this->insuranceCentreSubDomainName
     * @param string  $insuranceCentreId            Initialization value for $this->insuranceCentreId
     * @param string  $insuranceCompanyId           Initialization value for $this->insuranceCompanyId
     * @param bool    $isSearchQuery                Initialization value for $this->isSearchQuery
     * @param string  $giftCode                     Initialization value for $this->giftCode
     * @param string  $customerUserId               Initialization value for $this->customerUserId
     */
    public function __construct()
    {
        if (14 == func_num_args()) {
            $this->expertiseParamId             = func_get_arg(0);
            $this->isResident                   = func_get_arg(1);
            $this->isStudent                    = func_get_arg(2);
            $this->riskLevelId                  = func_get_arg(3);
            $this->activityAreaParamId          = func_get_arg(4);
            $this->commitmentCeilingParamId     = func_get_arg(5);
            $this->insuranceExtraCoverageIds    = func_get_arg(6);
            $this->policyTermId                 = func_get_arg(7);
            $this->insuranceCentreSubDomainName = func_get_arg(8);
            $this->insuranceCentreId            = func_get_arg(9);
            $this->insuranceCompanyId           = func_get_arg(10);
            $this->isSearchQuery                = func_get_arg(11);
            $this->giftCode                     = func_get_arg(12);
            $this->customerUserId               = func_get_arg(13);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['expertiseParamId']             = $this->expertiseParamId;
        $json['isResident']                   = $this->isResident;
        $json['isStudent']                    = $this->isStudent;
        $json['riskLevelId']                  = $this->riskLevelId;
        $json['activityAreaParamId']          = $this->activityAreaParamId;
        $json['commitmentCeilingParamId']     = $this->commitmentCeilingParamId;
        $json['insuranceExtraCoverageIds']    = $this->insuranceExtraCoverageIds;
        $json['policyTermId']                 = $this->policyTermId;
        $json['insuranceCentreSubDomainName'] = $this->insuranceCentreSubDomainName;
        $json['insuranceCentreId']            = $this->insuranceCentreId;
        $json['insuranceCompanyId']           = $this->insuranceCompanyId;
        $json['isSearchQuery']                = $this->isSearchQuery;
        $json['giftCode']                     = $this->giftCode;
        $json['customerUserId']               = $this->customerUserId;

        return $json;
    }
}
