<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PortalLandingPage implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $licensed public property
     */
    public $licensed;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceGroup[] $insuranceGroup public property
     */
    public $insuranceGroup;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $insuranceType public property
     */
    public $insuranceType;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\SummaryCard[] $summaryCards public property
     */
    public $summaryCards;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\SummaryNotic[] $summaryNotics public property
     */
    public $summaryNotics;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ImageAlbum[] $imageAlbums public property
     */
    public $imageAlbums;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\VideoGallery[] $videoGalleries public property
     */
    public $videoGalleries;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceCentre $insuranceCentre public property
     */
    public $insuranceCentre;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceCentrePortal $insuranceCentrePortal public property
     */
    public $insuranceCentrePortal;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool                  $licensed              Initialization value for $this->licensed
     * @param array                 $insuranceGroup        Initialization value for $this->insuranceGroup
     * @param array                 $insuranceType         Initialization value for $this->insuranceType
     * @param array                 $summaryCards          Initialization value for $this->summaryCards
     * @param array                 $summaryNotics         Initialization value for $this->summaryNotics
     * @param array                 $imageAlbums           Initialization value for $this->imageAlbums
     * @param array                 $videoGalleries        Initialization value for $this->videoGalleries
     * @param InsuranceCentre       $insuranceCentre       Initialization value for $this->insuranceCentre
     * @param InsuranceCentrePortal $insuranceCentrePortal Initialization value for $this->insuranceCentrePortal
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->licensed              = func_get_arg(0);
            $this->insuranceGroup        = func_get_arg(1);
            $this->insuranceType         = func_get_arg(2);
            $this->summaryCards          = func_get_arg(3);
            $this->summaryNotics         = func_get_arg(4);
            $this->imageAlbums           = func_get_arg(5);
            $this->videoGalleries        = func_get_arg(6);
            $this->insuranceCentre       = func_get_arg(7);
            $this->insuranceCentrePortal = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['licensed']              = $this->licensed;
        $json['insuranceGroup']        = $this->insuranceGroup;
        $json['insuranceType']         = $this->insuranceType;
        $json['summaryCards']          = $this->summaryCards;
        $json['summaryNotics']         = $this->summaryNotics;
        $json['imageAlbums']           = $this->imageAlbums;
        $json['videoGalleries']        = $this->videoGalleries;
        $json['insuranceCentre']       = $this->insuranceCentre;
        $json['insuranceCentrePortal'] = $this->insuranceCentrePortal;

        return $json;
    }
}
