<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SpecialPlan implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $key public property
     */
    public $key;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $count public property
     */
    public $count;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $policyType public property
     */
    public $policyType;

    /**
     * @todo Write general description for this property
     * @var string|null $display public property
     */
    public $display;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $iconPosition public property
     */
    public $iconPosition;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $key          Initialization value for $this->key
     * @param integer $count        Initialization value for $this->count
     * @param string  $title        Initialization value for $this->title
     * @param integer $policyType   Initialization value for $this->policyType
     * @param string  $display      Initialization value for $this->display
     * @param integer $iconPosition Initialization value for $this->iconPosition
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->key          = func_get_arg(0);
            $this->count        = func_get_arg(1);
            $this->title        = func_get_arg(2);
            $this->policyType   = func_get_arg(3);
            $this->display      = func_get_arg(4);
            $this->iconPosition = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['key']          = $this->key;
        $json['count']        = $this->count;
        $json['title']        = $this->title;
        $json['policyType']   = $this->policyType;
        $json['display']      = $this->display;
        $json['iconPosition'] = $this->iconPosition;

        return $json;
    }
}
