<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Status implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $entityId public property
     */
    public $entityId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $primaryEntityName public property
     */
    public $primaryEntityName;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $statusCollectionId public property
     */
    public $statusCollectionId;

    /**
     * @todo Write general description for this property
     * @var string|null $formData public property
     */
    public $formData;

    /**
     * @todo Write general description for this property
     * @var string|null $statusTitle public property
     */
    public $statusTitle;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $editable public property
     */
    public $editable;

    /**
     * @todo Write general description for this property
     * @var string|null $statusCollectionParentId public property
     */
    public $statusCollectionParentId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $id                       Initialization value for $this->id
     * @param string  $entityId                 Initialization value for $this->entityId
     * @param integer $primaryEntityName        Initialization value for $this->primaryEntityName
     * @param string  $statusCollectionId       Initialization value for $this->statusCollectionId
     * @param string  $formData                 Initialization value for $this->formData
     * @param string  $statusTitle              Initialization value for $this->statusTitle
     * @param bool    $editable                 Initialization value for $this->editable
     * @param string  $statusCollectionParentId Initialization value for $this->statusCollectionParentId
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->id                       = func_get_arg(0);
            $this->entityId                 = func_get_arg(1);
            $this->primaryEntityName        = func_get_arg(2);
            $this->statusCollectionId       = func_get_arg(3);
            $this->formData                 = func_get_arg(4);
            $this->statusTitle              = func_get_arg(5);
            $this->editable                 = func_get_arg(6);
            $this->statusCollectionParentId = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                       = $this->id;
        $json['entityId']                 = $this->entityId;
        $json['primaryEntityName']        = $this->primaryEntityName;
        $json['statusCollectionId']       = $this->statusCollectionId;
        $json['formData']                 = $this->formData;
        $json['statusTitle']              = $this->statusTitle;
        $json['editable']                 = $this->editable;
        $json['statusCollectionParentId'] = $this->statusCollectionParentId;

        return $json;
    }
}
