<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TargetSite implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps Name
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @maps AssemblyName
     * @var string $assemblyName public property
     */
    public $assemblyName;

    /**
     * @todo Write general description for this property
     * @required
     * @maps ClassName
     * @var string $className public property
     */
    public $className;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Signature
     * @var string $signature public property
     */
    public $signature;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Signature2
     * @var string $signature2 public property
     */
    public $signature2;

    /**
     * @todo Write general description for this property
     * @required
     * @maps MemberType
     * @var integer $memberType public property
     */
    public $memberType;

    /**
     * @todo Write general description for this property
     * @maps GenericArguments
     * @var string|null $genericArguments public property
     */
    public $genericArguments;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $name             Initialization value for $this->name
     * @param string  $assemblyName     Initialization value for $this->assemblyName
     * @param string  $className        Initialization value for $this->className
     * @param string  $signature        Initialization value for $this->signature
     * @param string  $signature2       Initialization value for $this->signature2
     * @param integer $memberType       Initialization value for $this->memberType
     * @param string  $genericArguments Initialization value for $this->genericArguments
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->name             = func_get_arg(0);
            $this->assemblyName     = func_get_arg(1);
            $this->className        = func_get_arg(2);
            $this->signature        = func_get_arg(3);
            $this->signature2       = func_get_arg(4);
            $this->memberType       = func_get_arg(5);
            $this->genericArguments = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Name']             = $this->name;
        $json['AssemblyName']     = $this->assemblyName;
        $json['ClassName']        = $this->className;
        $json['Signature']        = $this->signature;
        $json['Signature2']       = $this->signature2;
        $json['MemberType']       = $this->memberType;
        $json['GenericArguments'] = $this->genericArguments;

        return $json;
    }
}
