<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TrackingCode implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceTypeId public property
     */
    public $insuranceTypeId;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $insuranceCentreName public property
     */
    public $insuranceCentreName;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCompanyId public property
     */
    public $insuranceCompanyId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $insuranceCompanyTitle public property
     */
    public $insuranceCompanyTitle;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $insurancePolicyNumber public property
     */
    public $insurancePolicyNumber;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $personalityType public property
     */
    public $personalityType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $damageType public property
     */
    public $damageType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $nationalCode public property
     */
    public $nationalCode;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $mobile public property
     */
    public $mobile;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $insuredProfile public property
     */
    public $insuredProfile;

    /**
     * @todo Write general description for this property
     * @var string|null $refrencedUser public property
     */
    public $refrencedUser;

    /**
     * @todo Write general description for this property
     * @var string|null $referenceCount public property
     */
    public $referenceCount;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $trackingCode public property
     */
    public $trackingCode;

    /**
     * @todo Write general description for this property
     * @var string|null $paymentType public property
     */
    public $paymentType;

    /**
     * @todo Write general description for this property
     * @var string|null $paymentDate public property
     */
    public $paymentDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $paymentPersianDate public property
     */
    public $paymentPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $subDomain public property
     */
    public $subDomain;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceTypeTitle public property
     */
    public $insuranceTypeTitle;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOn public property
     */
    public $createOn;

    /**
     * @todo Write general description for this property
     * @var string|null $updateOn public property
     */
    public $updateOn;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $updateOnPersianDate public property
     */
    public $updateOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\TrackingDamageStatusTrackingCode[] $trackingDamageStatus public property
     */
    public $trackingDamageStatus;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                    Initialization value for $this->id
     * @param integer $insuranceTypeId       Initialization value for $this->insuranceTypeId
     * @param integer $insuranceCentreId     Initialization value for $this->insuranceCentreId
     * @param string  $insuranceCentreName   Initialization value for $this->insuranceCentreName
     * @param integer $insuranceCompanyId    Initialization value for $this->insuranceCompanyId
     * @param string  $insuranceCompanyTitle Initialization value for $this->insuranceCompanyTitle
     * @param string  $insurancePolicyNumber Initialization value for $this->insurancePolicyNumber
     * @param integer $personalityType       Initialization value for $this->personalityType
     * @param string  $damageType            Initialization value for $this->damageType
     * @param string  $name                  Initialization value for $this->name
     * @param string  $nationalCode          Initialization value for $this->nationalCode
     * @param string  $mobile                Initialization value for $this->mobile
     * @param string  $insuredProfile        Initialization value for $this->insuredProfile
     * @param string  $refrencedUser         Initialization value for $this->refrencedUser
     * @param string  $referenceCount        Initialization value for $this->referenceCount
     * @param string  $trackingCode          Initialization value for $this->trackingCode
     * @param string  $paymentType           Initialization value for $this->paymentType
     * @param string  $paymentDate           Initialization value for $this->paymentDate
     * @param string  $paymentPersianDate    Initialization value for $this->paymentPersianDate
     * @param string  $subDomain             Initialization value for $this->subDomain
     * @param string  $insuranceTypeTitle    Initialization value for $this->insuranceTypeTitle
     * @param string  $createOn              Initialization value for $this->createOn
     * @param string  $updateOn              Initialization value for $this->updateOn
     * @param string  $createOnPersianDate   Initialization value for $this->createOnPersianDate
     * @param string  $updateOnPersianDate   Initialization value for $this->updateOnPersianDate
     * @param array   $trackingDamageStatus  Initialization value for $this->trackingDamageStatus
     */
    public function __construct()
    {
        if (26 == func_num_args()) {
            $this->id                    = func_get_arg(0);
            $this->insuranceTypeId       = func_get_arg(1);
            $this->insuranceCentreId     = func_get_arg(2);
            $this->insuranceCentreName   = func_get_arg(3);
            $this->insuranceCompanyId    = func_get_arg(4);
            $this->insuranceCompanyTitle = func_get_arg(5);
            $this->insurancePolicyNumber = func_get_arg(6);
            $this->personalityType       = func_get_arg(7);
            $this->damageType            = func_get_arg(8);
            $this->name                  = func_get_arg(9);
            $this->nationalCode          = func_get_arg(10);
            $this->mobile                = func_get_arg(11);
            $this->insuredProfile        = func_get_arg(12);
            $this->refrencedUser         = func_get_arg(13);
            $this->referenceCount        = func_get_arg(14);
            $this->trackingCode          = func_get_arg(15);
            $this->paymentType           = func_get_arg(16);
            $this->paymentDate           = func_get_arg(17);
            $this->paymentPersianDate    = func_get_arg(18);
            $this->subDomain             = func_get_arg(19);
            $this->insuranceTypeTitle    = func_get_arg(20);
            $this->createOn              = func_get_arg(21);
            $this->updateOn              = func_get_arg(22);
            $this->createOnPersianDate   = func_get_arg(23);
            $this->updateOnPersianDate   = func_get_arg(24);
            $this->trackingDamageStatus  = func_get_arg(25);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                    = $this->id;
        $json['insuranceTypeId']       = $this->insuranceTypeId;
        $json['insuranceCentreId']     = $this->insuranceCentreId;
        $json['insuranceCentreName']   = $this->insuranceCentreName;
        $json['insuranceCompanyId']    = $this->insuranceCompanyId;
        $json['insuranceCompanyTitle'] = $this->insuranceCompanyTitle;
        $json['insurancePolicyNumber'] = $this->insurancePolicyNumber;
        $json['personalityType']       = $this->personalityType;
        $json['damageType']            = $this->damageType;
        $json['name']                  = $this->name;
        $json['nationalCode']          = $this->nationalCode;
        $json['mobile']                = $this->mobile;
        $json['insuredProfile']        = $this->insuredProfile;
        $json['refrencedUser']         = $this->refrencedUser;
        $json['referenceCount']        = $this->referenceCount;
        $json['trackingCode']          = $this->trackingCode;
        $json['paymentType']           = $this->paymentType;
        $json['paymentDate']           = $this->paymentDate;
        $json['paymentPersianDate']    = $this->paymentPersianDate;
        $json['subDomain']             = $this->subDomain;
        $json['insuranceTypeTitle']    = $this->insuranceTypeTitle;
        $json['createOn']              = $this->createOn;
        $json['updateOn']              = $this->updateOn;
        $json['createOnPersianDate']   = $this->createOnPersianDate;
        $json['updateOnPersianDate']   = $this->updateOnPersianDate;
        $json['trackingDamageStatus']  = $this->trackingDamageStatus;

        return $json;
    }
}
