<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TrackingDamageStatusTrackingCode implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $trackingDamageId public property
     */
    public $trackingDamageId;

    /**
     * @todo Write general description for this property
     * @var string|null $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $trackingDamageStatus public property
     */
    public $trackingDamageStatus;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\TrackingDamageFileTrackinCode[] $trackingDamageFile public property
     */
    public $trackingDamageFile;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                   Initialization value for $this->id
     * @param integer $trackingDamageId     Initialization value for $this->trackingDamageId
     * @param string  $description          Initialization value for $this->description
     * @param integer $trackingDamageStatus Initialization value for $this->trackingDamageStatus
     * @param array   $trackingDamageFile   Initialization value for $this->trackingDamageFile
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->id                   = func_get_arg(0);
            $this->trackingDamageId     = func_get_arg(1);
            $this->description          = func_get_arg(2);
            $this->trackingDamageStatus = func_get_arg(3);
            $this->trackingDamageFile   = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                   = $this->id;
        $json['trackingDamageId']     = $this->trackingDamageId;
        $json['description']          = $this->description;
        $json['trackingDamageStatus'] = $this->trackingDamageStatus;
        $json['trackingDamageFile']   = $this->trackingDamageFile;

        return $json;
    }
}
