<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TravelInsurance implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var bool $hasPlan public property
     */
    public $hasPlan;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isSamanInsurance public property
     */
    public $isSamanInsurance;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\Zone[] $zones public property
     */
    public $zones;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\TravelDuration[] $travelDurations public property
     */
    public $travelDurations;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\TravelAge[] $travelAges public property
     */
    public $travelAges;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\Province[] $provinces public property
     */
    public $provinces;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $cities public property
     */
    public $cities;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $cityRegions public property
     */
    public $cityRegions;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\ShippingType[] $shippingTypes public property
     */
    public $shippingTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\PostType[] $postTypes public property
     */
    public $postTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsuranceDataTravelInsurance $insuranceData public property
     */
    public $insuranceData;

    /**
     * @todo Write general description for this property
     * @required
     * @var \EasyBimehLandingLib\Models\InsurancePolicyCondition $insurancePolicyCondition public property
     */
    public $insurancePolicyCondition;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool                         $hasPlan                  Initialization value for $this->hasPlan
     * @param bool                         $isSamanInsurance         Initialization value for $this->isSamanInsurance
     * @param array                        $zones                    Initialization value for $this->zones
     * @param array                        $travelDurations          Initialization value for $this->travelDurations
     * @param array                        $travelAges               Initialization value for $this->travelAges
     * @param array                        $provinces                Initialization value for $this->provinces
     * @param array                        $cities                   Initialization value for $this->cities
     * @param array                        $cityRegions              Initialization value for $this->cityRegions
     * @param array                        $shippingTypes            Initialization value for $this->shippingTypes
     * @param array                        $postTypes                Initialization value for $this->postTypes
     * @param InsuranceDataTravelInsurance $insuranceData            Initialization value for $this->insuranceData
     * @param InsurancePolicyCondition     $insurancePolicyCondition Initialization value for $this-
     *                                                                 >insurancePolicyCondition
     */
    public function __construct()
    {
        if (12 == func_num_args()) {
            $this->hasPlan                  = func_get_arg(0);
            $this->isSamanInsurance         = func_get_arg(1);
            $this->zones                    = func_get_arg(2);
            $this->travelDurations          = func_get_arg(3);
            $this->travelAges               = func_get_arg(4);
            $this->provinces                = func_get_arg(5);
            $this->cities                   = func_get_arg(6);
            $this->cityRegions              = func_get_arg(7);
            $this->shippingTypes            = func_get_arg(8);
            $this->postTypes                = func_get_arg(9);
            $this->insuranceData            = func_get_arg(10);
            $this->insurancePolicyCondition = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['hasPlan']                  = $this->hasPlan;
        $json['isSamanInsurance']         = $this->isSamanInsurance;
        $json['zones']                    = $this->zones;
        $json['travelDurations']          = $this->travelDurations;
        $json['travelAges']               = $this->travelAges;
        $json['provinces']                = $this->provinces;
        $json['cities']                   = $this->cities;
        $json['cityRegions']              = $this->cityRegions;
        $json['shippingTypes']            = $this->shippingTypes;
        $json['postTypes']                = $this->postTypes;
        $json['insuranceData']            = $this->insuranceData;
        $json['insurancePolicyCondition'] = $this->insurancePolicyCondition;

        return $json;
    }
}
