<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TravelInsurancePolicyFilter implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var string|null $zoneIds public property
     */
    public $zoneIds;

    /**
     * @todo Write general description for this property
     * @var string|null $travelRatePlanId public property
     */
    public $travelRatePlanId;

    /**
     * @todo Write general description for this property
     * @var string|null $travelInsurancePolicyExtendAges public property
     */
    public $travelInsurancePolicyExtendAges;

    /**
     * @todo Write general description for this property
     * @var string|null $travelDurationParam public property
     */
    public $travelDurationParam;

    /**
     * @todo Write general description for this property
     * @var string|null $birthDatePersian public property
     */
    public $birthDatePersian;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceExtraCoverageIds public property
     */
    public $insuranceExtraCoverageIds;

    /**
     * @todo Write general description for this property
     * @var string|null $policyTermId public property
     */
    public $policyTermId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreSubDomainName public property
     */
    public $insuranceCentreSubDomainName;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCentreId public property
     */
    public $insuranceCentreId;

    /**
     * @todo Write general description for this property
     * @var string|null $insuranceCompanyId public property
     */
    public $insuranceCompanyId;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isSearchQuery public property
     */
    public $isSearchQuery;

    /**
     * @todo Write general description for this property
     * @var string|null $giftCode public property
     */
    public $giftCode;

    /**
     * @todo Write general description for this property
     * @var string|null $customerUserId public property
     */
    public $customerUserId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $zoneIds                         Initialization value for $this->zoneIds
     * @param string $travelRatePlanId                Initialization value for $this->travelRatePlanId
     * @param string $travelInsurancePolicyExtendAges Initialization value for $this->travelInsurancePolicyExtendAges
     * @param string $travelDurationParam             Initialization value for $this->travelDurationParam
     * @param string $birthDatePersian                Initialization value for $this->birthDatePersian
     * @param string $insuranceExtraCoverageIds       Initialization value for $this->insuranceExtraCoverageIds
     * @param string $policyTermId                    Initialization value for $this->policyTermId
     * @param string $insuranceCentreSubDomainName    Initialization value for $this->insuranceCentreSubDomainName
     * @param string $insuranceCentreId               Initialization value for $this->insuranceCentreId
     * @param string $insuranceCompanyId              Initialization value for $this->insuranceCompanyId
     * @param bool   $isSearchQuery                   Initialization value for $this->isSearchQuery
     * @param string $giftCode                        Initialization value for $this->giftCode
     * @param string $customerUserId                  Initialization value for $this->customerUserId
     */
    public function __construct()
    {
        if (13 == func_num_args()) {
            $this->zoneIds                         = func_get_arg(0);
            $this->travelRatePlanId                = func_get_arg(1);
            $this->travelInsurancePolicyExtendAges = func_get_arg(2);
            $this->travelDurationParam             = func_get_arg(3);
            $this->birthDatePersian                = func_get_arg(4);
            $this->insuranceExtraCoverageIds       = func_get_arg(5);
            $this->policyTermId                    = func_get_arg(6);
            $this->insuranceCentreSubDomainName    = func_get_arg(7);
            $this->insuranceCentreId               = func_get_arg(8);
            $this->insuranceCompanyId              = func_get_arg(9);
            $this->isSearchQuery                   = func_get_arg(10);
            $this->giftCode                        = func_get_arg(11);
            $this->customerUserId                  = func_get_arg(12);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['zoneIds']                         = $this->zoneIds;
        $json['travelRatePlanId']                = $this->travelRatePlanId;
        $json['travelInsurancePolicyExtendAges'] = $this->travelInsurancePolicyExtendAges;
        $json['travelDurationParam']             = $this->travelDurationParam;
        $json['birthDatePersian']                = $this->birthDatePersian;
        $json['insuranceExtraCoverageIds']       = $this->insuranceExtraCoverageIds;
        $json['policyTermId']                    = $this->policyTermId;
        $json['insuranceCentreSubDomainName']    = $this->insuranceCentreSubDomainName;
        $json['insuranceCentreId']               = $this->insuranceCentreId;
        $json['insuranceCompanyId']              = $this->insuranceCompanyId;
        $json['isSearchQuery']                   = $this->isSearchQuery;
        $json['giftCode']                        = $this->giftCode;
        $json['customerUserId']                  = $this->customerUserId;

        return $json;
    }
}
