<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TravelInsurancePolicyExtend implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insurancePolicyId public property
     */
    public $insurancePolicyId;

    /**
     * @todo Write general description for this property
     * @var string|null $travelDurationParam public property
     */
    public $travelDurationParam;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $passengersCount public property
     */
    public $passengersCount;

    /**
     * @todo Write general description for this property
     * @var string|null $birthDate public property
     */
    public $birthDate;

    /**
     * @todo Write general description for this property
     * @var string|null $birthDatePersian public property
     */
    public $birthDatePersian;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $riskLevelDiscount public property
     */
    public $riskLevelDiscount;

    /**
     * @todo Write general description for this property
     * @var string|null $basePremium public property
     */
    public $basePremium;

    /**
     * @todo Write general description for this property
     * @var string|null $allPremium public property
     */
    public $allPremium;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCompanyDiscountRate public property
     */
    public $insuranceCompanyDiscountRate;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCompanyDiscount public property
     */
    public $insuranceCompanyDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $insuranceCentreDiscount public property
     */
    public $insuranceCentreDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $coupenDiscount public property
     */
    public $coupenDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $allDiscount public property
     */
    public $allDiscount;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $exchangePremium public property
     */
    public $exchangePremium;

    /**
     * @todo Write general description for this property
     * @var string|null $travelRatePlanId public property
     */
    public $travelRatePlanId;

    /**
     * @todo Write general description for this property
     * @var string|null $planTitle public property
     */
    public $planTitle;

    /**
     * @todo Write general description for this property
     * @var string|null $travelInsurancePolicyExtendAges public property
     */
    public $travelInsurancePolicyExtendAges;

    /**
     * @todo Write general description for this property
     * @var string|null $travelInsurancePolicyExtendPassengers public property
     */
    public $travelInsurancePolicyExtendPassengers;

    /**
     * @todo Write general description for this property
     * @var string|null $zoneIds public property
     */
    public $zoneIds;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $insurancePolicyId                     Initialization value for $this->insurancePolicyId
     * @param string  $travelDurationParam                   Initialization value for $this->travelDurationParam
     * @param integer $passengersCount                       Initialization value for $this->passengersCount
     * @param string  $birthDate                             Initialization value for $this->birthDate
     * @param string  $birthDatePersian                      Initialization value for $this->birthDatePersian
     * @param integer $riskLevelDiscount                     Initialization value for $this->riskLevelDiscount
     * @param string  $basePremium                           Initialization value for $this->basePremium
     * @param string  $allPremium                            Initialization value for $this->allPremium
     * @param integer $insuranceCompanyDiscountRate          Initialization value for $this-
     *                                                         >insuranceCompanyDiscountRate
     * @param integer $insuranceCompanyDiscount              Initialization value for $this->insuranceCompanyDiscount
     * @param integer $insuranceCentreDiscount               Initialization value for $this->insuranceCentreDiscount
     * @param integer $coupenDiscount                        Initialization value for $this->coupenDiscount
     * @param integer $allDiscount                           Initialization value for $this->allDiscount
     * @param integer $exchangePremium                       Initialization value for $this->exchangePremium
     * @param string  $travelRatePlanId                      Initialization value for $this->travelRatePlanId
     * @param string  $planTitle                             Initialization value for $this->planTitle
     * @param string  $travelInsurancePolicyExtendAges       Initialization value for $this-
     *                                                         >travelInsurancePolicyExtendAges
     * @param string  $travelInsurancePolicyExtendPassengers Initialization value for $this-
     *                                                         >travelInsurancePolicyExtendPassengers
     * @param string  $zoneIds                               Initialization value for $this->zoneIds
     */
    public function __construct()
    {
        if (19 == func_num_args()) {
            $this->insurancePolicyId                     = func_get_arg(0);
            $this->travelDurationParam                   = func_get_arg(1);
            $this->passengersCount                       = func_get_arg(2);
            $this->birthDate                             = func_get_arg(3);
            $this->birthDatePersian                      = func_get_arg(4);
            $this->riskLevelDiscount                     = func_get_arg(5);
            $this->basePremium                           = func_get_arg(6);
            $this->allPremium                            = func_get_arg(7);
            $this->insuranceCompanyDiscountRate          = func_get_arg(8);
            $this->insuranceCompanyDiscount              = func_get_arg(9);
            $this->insuranceCentreDiscount               = func_get_arg(10);
            $this->coupenDiscount                        = func_get_arg(11);
            $this->allDiscount                           = func_get_arg(12);
            $this->exchangePremium                       = func_get_arg(13);
            $this->travelRatePlanId                      = func_get_arg(14);
            $this->planTitle                             = func_get_arg(15);
            $this->travelInsurancePolicyExtendAges       = func_get_arg(16);
            $this->travelInsurancePolicyExtendPassengers = func_get_arg(17);
            $this->zoneIds                               = func_get_arg(18);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['insurancePolicyId']                     = $this->insurancePolicyId;
        $json['travelDurationParam']                   = $this->travelDurationParam;
        $json['passengersCount']                       = $this->passengersCount;
        $json['birthDate']                             = $this->birthDate;
        $json['birthDatePersian']                      = $this->birthDatePersian;
        $json['riskLevelDiscount']                     = $this->riskLevelDiscount;
        $json['basePremium']                           = $this->basePremium;
        $json['allPremium']                            = $this->allPremium;
        $json['insuranceCompanyDiscountRate']          = $this->insuranceCompanyDiscountRate;
        $json['insuranceCompanyDiscount']              = $this->insuranceCompanyDiscount;
        $json['insuranceCentreDiscount']               = $this->insuranceCentreDiscount;
        $json['coupenDiscount']                        = $this->coupenDiscount;
        $json['allDiscount']                           = $this->allDiscount;
        $json['exchangePremium']                       = $this->exchangePremium;
        $json['travelRatePlanId']                      = $this->travelRatePlanId;
        $json['planTitle']                             = $this->planTitle;
        $json['travelInsurancePolicyExtendAges']       = $this->travelInsurancePolicyExtendAges;
        $json['travelInsurancePolicyExtendPassengers'] = $this->travelInsurancePolicyExtendPassengers;
        $json['zoneIds']                               = $this->zoneIds;

        return $json;
    }
}
