<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 *اطلاعات فایل آپلود شده
 */
class Upload implements JsonSerializable
{
    /**
     * شناسه ی فایل
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * شناسه ی دایرکتوری فایل
     * @required
     * @var integer $metaMediaDirectoryId public property
     */
    public $metaMediaDirectoryId;

    /**
     * عنوان
     * @var string|null $title public property
     */
    public $title;

    /**
     * توضیح فایل
     * @var string|null $alt public property
     */
    public $alt;

    /**
     * نام فایل
     * @required
     * @var string $fileName public property
     */
    public $fileName;

    /**
     * پسورد فایل
     * @var string|null $passwordHash public property
     */
    public $passwordHash;

    /**
     * وضعیت اکتیو بودن فایل
     * @var string|null $isActive public property
     */
    public $isActive;

    /**
     * زمان انقضای فایل
     * @var string|null $expireOn public property
     */
    public $expireOn;

    /**
     * لیبل دسته بندی فایل
     * @var string|null $fileLibraryLabelParam public property
     */
    public $fileLibraryLabelParam;

    /**
     * اندازه ی فایل
     * @var string|null $fileSize public property
     */
    public $fileSize;

    /**
     * اندازه ی فایل
     * @required
     * @var string $fileSizeValue public property
     */
    public $fileSizeValue;

    /**
     * آدرس فایل
     * @required
     * @var string $fileUrl public property
     */
    public $fileUrl;

    /**
     * آدرس پیش نمایش فایل
     * @required
     * @var string $fileThumbnailUrl public property
     */
    public $fileThumbnailUrl;

    /**
     * تاریخ انقضای شمسی
     * @required
     * @var string $expireOnPersianDate public property
     */
    public $expireOnPersianDate;

    /**
     * تاریخ بروز رسانی فایل
     * @required
     * @var string $updateOn public property
     */
    public $updateOn;

    /**
     * تاریخ ثبت فایل
     * @required
     * @var string $createOn public property
     */
    public $createOn;

    /**
     * تاریخ ثبت فایل شمسی
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * تاریخ بروز رسانی فایل شمسی
     * @required
     * @var string $updateOnPersianDate public property
     */
    public $updateOnPersianDate;

    /**
     * آدرس دایرکتوری فایل
     * @required
     * @var string $filePath public property
     */
    public $filePath;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                    Initialization value for $this->id
     * @param integer $metaMediaDirectoryId  Initialization value for $this->metaMediaDirectoryId
     * @param string  $title                 Initialization value for $this->title
     * @param string  $alt                   Initialization value for $this->alt
     * @param string  $fileName              Initialization value for $this->fileName
     * @param string  $passwordHash          Initialization value for $this->passwordHash
     * @param string  $isActive              Initialization value for $this->isActive
     * @param string  $expireOn              Initialization value for $this->expireOn
     * @param string  $fileLibraryLabelParam Initialization value for $this->fileLibraryLabelParam
     * @param string  $fileSize              Initialization value for $this->fileSize
     * @param string  $fileSizeValue         Initialization value for $this->fileSizeValue
     * @param string  $fileUrl               Initialization value for $this->fileUrl
     * @param string  $fileThumbnailUrl      Initialization value for $this->fileThumbnailUrl
     * @param string  $expireOnPersianDate   Initialization value for $this->expireOnPersianDate
     * @param string  $updateOn              Initialization value for $this->updateOn
     * @param string  $createOn              Initialization value for $this->createOn
     * @param string  $createOnPersianDate   Initialization value for $this->createOnPersianDate
     * @param string  $updateOnPersianDate   Initialization value for $this->updateOnPersianDate
     * @param string  $filePath              Initialization value for $this->filePath
     */
    public function __construct()
    {
        if (19 == func_num_args()) {
            $this->id                    = func_get_arg(0);
            $this->metaMediaDirectoryId  = func_get_arg(1);
            $this->title                 = func_get_arg(2);
            $this->alt                   = func_get_arg(3);
            $this->fileName              = func_get_arg(4);
            $this->passwordHash          = func_get_arg(5);
            $this->isActive              = func_get_arg(6);
            $this->expireOn              = func_get_arg(7);
            $this->fileLibraryLabelParam = func_get_arg(8);
            $this->fileSize              = func_get_arg(9);
            $this->fileSizeValue         = func_get_arg(10);
            $this->fileUrl               = func_get_arg(11);
            $this->fileThumbnailUrl      = func_get_arg(12);
            $this->expireOnPersianDate   = func_get_arg(13);
            $this->updateOn              = func_get_arg(14);
            $this->createOn              = func_get_arg(15);
            $this->createOnPersianDate   = func_get_arg(16);
            $this->updateOnPersianDate   = func_get_arg(17);
            $this->filePath              = func_get_arg(18);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                    = $this->id;
        $json['metaMediaDirectoryId']  = $this->metaMediaDirectoryId;
        $json['title']                 = $this->title;
        $json['alt']                   = $this->alt;
        $json['fileName']              = $this->fileName;
        $json['passwordHash']          = $this->passwordHash;
        $json['isActive']              = $this->isActive;
        $json['expireOn']              = $this->expireOn;
        $json['fileLibraryLabelParam'] = $this->fileLibraryLabelParam;
        $json['fileSize']              = $this->fileSize;
        $json['fileSizeValue']         = $this->fileSizeValue;
        $json['fileUrl']               = $this->fileUrl;
        $json['fileThumbnailUrl']      = $this->fileThumbnailUrl;
        $json['expireOnPersianDate']   = $this->expireOnPersianDate;
        $json['updateOn']              = $this->updateOn;
        $json['createOn']              = $this->createOn;
        $json['createOnPersianDate']   = $this->createOnPersianDate;
        $json['updateOnPersianDate']   = $this->updateOnPersianDate;
        $json['filePath']              = $this->filePath;

        return $json;
    }
}
