<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class VideoGallery implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $galleryType public property
     */
    public $galleryType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @var string|null $alt public property
     */
    public $alt;

    /**
     * @todo Write general description for this property
     * @var string|null $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isActive public property
     */
    public $isActive;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isMain public property
     */
    public $isMain;

    /**
     * @todo Write general description for this property
     * @required
     * @var bool $isAttachFile public property
     */
    public $isAttachFile;

    /**
     * @todo Write general description for this property
     * @var string|null $sortPriority public property
     */
    public $sortPriority;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $createOnPersianDate public property
     */
    public $createOnPersianDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $metaMediaFileId public property
     */
    public $metaMediaFileId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $metaMediaFileUrl public property
     */
    public $metaMediaFileUrl;

    /**
     * @todo Write general description for this property
     * @var string|null $metaMediaFileThumbnailUrl public property
     */
    public $metaMediaFileThumbnailUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $popupImageGalleryies public property
     */
    public $popupImageGalleryies;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $galleryDetails public property
     */
    public $galleryDetails;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id                        Initialization value for $this->id
     * @param integer $galleryType               Initialization value for $this->galleryType
     * @param string  $title                     Initialization value for $this->title
     * @param string  $alt                       Initialization value for $this->alt
     * @param string  $description               Initialization value for $this->description
     * @param bool    $isActive                  Initialization value for $this->isActive
     * @param bool    $isMain                    Initialization value for $this->isMain
     * @param bool    $isAttachFile              Initialization value for $this->isAttachFile
     * @param string  $sortPriority              Initialization value for $this->sortPriority
     * @param string  $createOnPersianDate       Initialization value for $this->createOnPersianDate
     * @param integer $metaMediaFileId           Initialization value for $this->metaMediaFileId
     * @param string  $metaMediaFileUrl          Initialization value for $this->metaMediaFileUrl
     * @param string  $metaMediaFileThumbnailUrl Initialization value for $this->metaMediaFileThumbnailUrl
     * @param array   $popupImageGalleryies      Initialization value for $this->popupImageGalleryies
     * @param array   $galleryDetails            Initialization value for $this->galleryDetails
     */
    public function __construct()
    {
        if (15 == func_num_args()) {
            $this->id                        = func_get_arg(0);
            $this->galleryType               = func_get_arg(1);
            $this->title                     = func_get_arg(2);
            $this->alt                       = func_get_arg(3);
            $this->description               = func_get_arg(4);
            $this->isActive                  = func_get_arg(5);
            $this->isMain                    = func_get_arg(6);
            $this->isAttachFile              = func_get_arg(7);
            $this->sortPriority              = func_get_arg(8);
            $this->createOnPersianDate       = func_get_arg(9);
            $this->metaMediaFileId           = func_get_arg(10);
            $this->metaMediaFileUrl          = func_get_arg(11);
            $this->metaMediaFileThumbnailUrl = func_get_arg(12);
            $this->popupImageGalleryies      = func_get_arg(13);
            $this->galleryDetails            = func_get_arg(14);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                        = $this->id;
        $json['galleryType']               = $this->galleryType;
        $json['title']                     = $this->title;
        $json['alt']                       = $this->alt;
        $json['description']               = $this->description;
        $json['isActive']                  = $this->isActive;
        $json['isMain']                    = $this->isMain;
        $json['isAttachFile']              = $this->isAttachFile;
        $json['sortPriority']              = $this->sortPriority;
        $json['createOnPersianDate']       = $this->createOnPersianDate;
        $json['metaMediaFileId']           = $this->metaMediaFileId;
        $json['metaMediaFileUrl']          = $this->metaMediaFileUrl;
        $json['metaMediaFileThumbnailUrl'] = $this->metaMediaFileThumbnailUrl;
        $json['popupImageGalleryies']      = $this->popupImageGalleryies;
        $json['galleryDetails']            = $this->galleryDetails;

        return $json;
    }
}
