<?php
/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace EasyBimehLandingLib;

use EasyBimehLandingLib\Controllers;

/**
 * EasyBimehLandingLib client class
 */
class EasyBimehLandingClient
{
    /**
     * Singleton access to FileManager controller
     * @return Controllers\FileManagerController The *Singleton* instance
     */
    public function getFileManager()
    {
        return Controllers\FileManagerController::getInstance();
    }
    /**
     * Singleton access to LiabilityDoctorInsurance controller
     * @return Controllers\LiabilityDoctorInsuranceController The *Singleton* instance
     */
    public function getLiabilityDoctorInsurance()
    {
        return Controllers\LiabilityDoctorInsuranceController::getInstance();
    }
    /**
     * Singleton access to CarBody controller
     * @return Controllers\CarBodyController The *Singleton* instance
     */
    public function getCarBody()
    {
        return Controllers\CarBodyController::getInstance();
    }
    /**
     * Singleton access to ElectronicEquipmentInsurance controller
     * @return Controllers\ElectronicEquipmentInsuranceController The *Singleton* instance
     */
    public function getElectronicEquipmentInsurance()
    {
        return Controllers\ElectronicEquipmentInsuranceController::getInstance();
    }
    /**
     * Singleton access to OtherInsuranceTypes controller
     * @return Controllers\OtherInsuranceTypesController The *Singleton* instance
     */
    public function getOtherInsuranceTypes()
    {
        return Controllers\OtherInsuranceTypesController::getInstance();
    }
    /**
     * Singleton access to ThirdPartyInsurance controller
     * @return Controllers\ThirdPartyInsuranceController The *Singleton* instance
     */
    public function getThirdPartyInsurance()
    {
        return Controllers\ThirdPartyInsuranceController::getInstance();
    }
    /**
     * Singleton access to MotorcycleInsurance controller
     * @return Controllers\MotorcycleInsuranceController The *Singleton* instance
     */
    public function getMotorcycleInsurance()
    {
        return Controllers\MotorcycleInsuranceController::getInstance();
    }
    /**
     * Singleton access to FireInsurance controller
     * @return Controllers\FireInsuranceController The *Singleton* instance
     */
    public function getFireInsurance()
    {
        return Controllers\FireInsuranceController::getInstance();
    }
    /**
     * Singleton access to EarthquakeInsurance controller
     * @return Controllers\EarthquakeInsuranceController The *Singleton* instance
     */
    public function getEarthquakeInsurance()
    {
        return Controllers\EarthquakeInsuranceController::getInstance();
    }
    /**
     * Singleton access to TravelInsurance controller
     * @return Controllers\TravelInsuranceController The *Singleton* instance
     */
    public function getTravelInsurance()
    {
        return Controllers\TravelInsuranceController::getInstance();
    }
    /**
     * Singleton access to ElevatorInsurance controller
     * @return Controllers\ElevatorInsuranceController The *Singleton* instance
     */
    public function getElevatorInsurance()
    {
        return Controllers\ElevatorInsuranceController::getInstance();
    }
    /**
     * Singleton access to Main controller
     * @return Controllers\MainController The *Singleton* instance
     */
    public function getMain()
    {
        return Controllers\MainController::getInstance();
    }
    /**
     * Singleton access to ComboData controller
     * @return Controllers\ComboDataController The *Singleton* instance
     */
    public function getComboData()
    {
        return Controllers\ComboDataController::getInstance();
    }
    /**
     * Singleton access to TrackingDamage controller
     * @return Controllers\TrackingDamageController The *Singleton* instance
     */
    public function getTrackingDamage()
    {
        return Controllers\TrackingDamageController::getInstance();
    }
    /**
     * Singleton access to Footer controller
     * @return Controllers\FooterController The *Singleton* instance
     */
    public function getFooter()
    {
        return Controllers\FooterController::getInstance();
    }
    /**
     * Singleton access to InsurancePolicyPlan controller
     * @return Controllers\InsurancePolicyPlanController The *Singleton* instance
     */
    public function getInsurancePolicyPlan()
    {
        return Controllers\InsurancePolicyPlanController::getInstance();
    }
}
